-- File was auto generated using the emoji-name-map npm package

local ee = ESOEmoji

local customShortcodes = { -- These will be used to turn :blah: into a blah emoji
	-- alliance war
	-- campaign pop
--	["gh_pop"] = {func = ee.Pop(102)},
--	["rw_pop"] = {func = ee.Pop(103)},
	-- alliances
	["ad"] = {
		func = {
			icon = "esoui/art/campaign/gamepad/gp_overview_allianceicon_aldmeri.dds",
			location = 0,
			size = 25,
			colour = nil,
		},
	},
	["ep"] = {
		func = {
			icon = "esoui/art/campaign/gamepad/gp_overview_allianceicon_ebonheart.dds",
			location = 0,
			size = 25,
			colour = nil,
		},
	},
	["dc"] = {
		func = {
			icon = "esoui/art/campaign/gamepad/gp_overview_allianceicon_daggerfall.dds",
			location = 0,
			size = 25,
			colour = nil,
		},
	},
	["ad_c"] = {
		func = {
			icon = "esoui/art/campaign/gamepad/gp_overview_allianceicon_aldmeri.dds",
			location = 0,
			size = 25,
			colour = "FFD700",
		},
	},
	["ep_c"] = {
		func = {
			icon = "esoui/art/campaign/gamepad/gp_overview_allianceicon_ebonheart.dds",
			location = 0,
			size = 25,
			colour = "FF2400",
		},
	},
	["dc_c"] = {
		func = {
			icon = "esoui/art/campaign/gamepad/gp_overview_allianceicon_daggerfall.dds",
			location = 0,
			size = 25,
			colour = "0096FF",
		},
	},
	-- buildings
	["keep"] = {
		func = {
			icon = "esoui/art/worldmap/map_ava_tabicon_keepsummary_up.dds",
			location = 0,
			size = nil,
			colour = nil,
		},
	},
	["castle"] = {
		func = {
			icon = "esoui/art/worldmap/map_ava_tabicon_keepsummary_up.dds",
			location = 0,
			size = nil,
			colour = nil,
		},
	},
	["fort"] = {
		func = {
			icon = "esoui/art/worldmap/map_ava_tabicon_keepsummary_up.dds",
			location = 0,
			size = nil,
			colour = nil,
		},
	},
--	["mine"] = {func = ee.GetTextureLinkIcon("esoui/art/worldmap/map_ava_tabicon_oremine_up.dds", 0)},
--	["farm"] = {func = ee.GetTextureLinkIcon("esoui/art/worldmap/map_ava_tabicon_foodfarm_up.dds", 0)},
--	["lumber"] = {func = ee.GetTextureLinkIcon("esoui/art/worldmap/map_ava_tabicon_woodmill_up.dds", 0)},
--	["lm"] = {func = ee.GetTextureLinkIcon("esoui/art/worldmap/map_ava_tabicon_woodmill_up.dds", 0)},
	
	-- characters
	-- classes
	-- dk
	["magdk"] = {
		func = {
			icon = "magdk.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	["stamdk"] = {
		func = {
			icon = "stamdk.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	-- templar
	["magplar"] = {
		func = {
			icon = "magplar.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	["stamplar"] = {
		func = {
			icon = "stamplar.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	-- nightblade
	["magblade"] = {
		func = {
			icon = "magblade.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	["stamblade"] = {
		func = {
			icon = "stamblade.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	-- sorc
	["magsorc"] = {
		func = {
			icon = "magsorc.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	["stamsorc"] = {
		func = {
			icon = "stamsorc.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	-- warden
	["magden"] = {
		func = {
			icon = "magden.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	["stamden"] = {
		func = {
			icon = "stamden.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	-- necro
	["magcro"] = {
		func = {
			icon = "magcro.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	["stamcro"] = {
		func = {
			icon = "stamcro.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	-- curses
	["vampire"] = {
		func = {
			icon = "vampire.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	["werewolf"] = {
		func = {
			icon = "werewolf.dds",
			location = 1,
			size = 28,
			colour = nil,
		},
	},
	-- cp
	["cp"] = {
		func = {
			icon = "esoui/art/champion/champion_icon.dds",
			location = 0,
			size = 20,
			colour = nil,
		},
	},
	
	-- Items
	-- gold
	["g"] = {
		func = {
			icon = "esoui/art/loot/icon_goldcoin_pressed.dds",
			location = 0,
			size = nil,
			colour = nil,
		},
	},
	["gold"] = {
		func = {
			icon = "esoui/art/loot/icon_goldcoin_pressed.dds",
			location = 0,
			size = nil,
			colour = nil,
		},
	},
	-- |t28:28:ESOEmoji\icons\coins.dds|t
	-- |t20:20:ESOEmoji\icons\Immersive-dds\gold_dark.dds|t
	-- |t20:20:ESOEmoji\icons\Immersive-dds\gold_light.dds|t
}


ee.emojiSCs = {
	["100"] = {unicode = "1F4AF"},
	["1234"] = {unicode = "1F522"},
	["grinning"] = {unicode = "1F600"},
	["grimacing"] = {unicode = "1F62C"},
	["grin"] = {unicode = "1F601"},
	["joy"] = {unicode = "1F602"},
	["rofl"] = {unicode = "1F923"},
	["partying"] = {unicode = "1F973"},
	["smiley"] = {unicode = "1F603"},
	["smile"] = {unicode = "1F604"},
	["sweat_smile"] = {unicode = "1F605"},
	["laughing"] = {unicode = "1F606"},
	["innocent"] = {unicode = "1F607"},
	["wink"] = {unicode = "1F609"},
	["blush"] = {unicode = "1F60A"},
	["slightly_smiling_face"] = {unicode = "1F642"},
	["upside_down_face"] = {unicode = "1F643"},
	["relaxed"] = {unicode = "263A"},
	["yum"] = {unicode = "1F60B"},
	["relieved"] = {unicode = "1F60C"},
	["heart_eyes"] = {unicode = "1F60D"},
	["smiling_face_with_three_hearts"] = {unicode = "1F970"},
	["kissing_heart"] = {unicode = "1F618"},
	["kissing"] = {unicode = "1F617"},
	["kissing_smiling_eyes"] = {unicode = "1F619"},
	["kissing_closed_eyes"] = {unicode = "1F61A"},
	["stuck_out_tongue_winking_eye"] = {unicode = "1F61C"},
	["zany"] = {unicode = "1F92A"},
	["raised_eyebrow"] = {unicode = "1F928"},
	["monocle"] = {unicode = "1F9D0"},
	["stuck_out_tongue_closed_eyes"] = {unicode = "1F61D"},
	["stuck_out_tongue"] = {unicode = "1F61B"},
	["money_mouth_face"] = {unicode = "1F911"},
	["nerd_face"] = {unicode = "1F913"},
	["sunglasses"] = {unicode = "1F60E"},
	["star_struck"] = {unicode = "1F929"},
	["clown_face"] = {unicode = "1F921"},
	["cowboy_hat_face"] = {unicode = "1F920"},
	["hugs"] = {unicode = "1F917"},
	["smirk"] = {unicode = "1F60F"},
	["no_mouth"] = {unicode = "1F636"},
	["neutral_face"] = {unicode = "1F610"},
	["expressionless"] = {unicode = "1F611"},
	["unamused"] = {unicode = "1F612"},
	["roll_eyes"] = {unicode = "1F644"},
	["thinking"] = {unicode = "1F914"},
	["lying_face"] = {unicode = "1F925"},
	["hand_over_mouth"] = {unicode = "1F92D"},
	["shushing"] = {unicode = "1F92B"},
	["symbols_over_mouth"] = {unicode = "1F92C"},
	["exploding_head"] = {unicode = "1F92F"},
	["flushed"] = {unicode = "1F633"},
	["disappointed"] = {unicode = "1F61E"},
	["worried"] = {unicode = "1F61F"},
	["angry"] = {unicode = "1F620"},
	["rage"] = {unicode = "1F621"},
	["pensive"] = {unicode = "1F614"},
	["confused"] = {unicode = "1F615"},
	["slightly_frowning_face"] = {unicode = "1F641"},
	["frowning_face"] = {unicode = "2639"},
	["persevere"] = {unicode = "1F623"},
	["confounded"] = {unicode = "1F616"},
	["tired_face"] = {unicode = "1F62B"},
	["weary"] = {unicode = "1F629"},
	["pleading"] = {unicode = "1F97A"},
	["triumph"] = {unicode = "1F624"},
	["open_mouth"] = {unicode = "1F62E"},
	["scream"] = {unicode = "1F631"},
	["fearful"] = {unicode = "1F628"},
	["cold_sweat"] = {unicode = "1F630"},
	["hushed"] = {unicode = "1F62F"},
	["frowning"] = {unicode = "1F626"},
	["anguished"] = {unicode = "1F627"},
	["cry"] = {unicode = "1F622"},
	["disappointed_relieved"] = {unicode = "1F625"},
	["drooling_face"] = {unicode = "1F924"},
	["sleepy"] = {unicode = "1F62A"},
	["sweat"] = {unicode = "1F613"},
	["hot"] = {unicode = "1F975"},
	["cold"] = {unicode = "1F976"},
	["sob"] = {unicode = "1F62D"},
	["dizzy_face"] = {unicode = "1F635"},
	["astonished"] = {unicode = "1F632"},
	["zipper_mouth_face"] = {unicode = "1F910"},
	["nauseated_face"] = {unicode = "1F922"},
	["sneezing_face"] = {unicode = "1F927"},
	["vomiting"] = {unicode = "1F92E"},
	["mask"] = {unicode = "1F637"},
	["face_with_thermometer"] = {unicode = "1F912"},
	["face_with_head_bandage"] = {unicode = "1F915"},
	["woozy"] = {unicode = "1F974"},
	["sleeping"] = {unicode = "1F634"},
	["zzz"] = {unicode = "1F4A4"},
	["poop"] = {unicode = "1F4A9"},
	["smiling_imp"] = {unicode = "1F608"},
	["imp"] = {unicode = "1F47F"},
	["japanese_ogre"] = {unicode = "1F479"},
	["japanese_goblin"] = {unicode = "1F47A"},
	["skull"] = {unicode = "1F480"},
	["ghost"] = {unicode = "1F47B"},
	["alien"] = {unicode = "1F47D"},
	["robot"] = {unicode = "1F916"},
	["smiley_cat"] = {unicode = "1F63A"},
	["smile_cat"] = {unicode = "1F638"},
	["joy_cat"] = {unicode = "1F639"},
	["heart_eyes_cat"] = {unicode = "1F63B"},
	["smirk_cat"] = {unicode = "1F63C"},
	["kissing_cat"] = {unicode = "1F63D"},
	["scream_cat"] = {unicode = "1F640"},
	["crying_cat_face"] = {unicode = "1F63F"},
	["pouting_cat"] = {unicode = "1F63E"},
	["palms_up"] = {unicode = "1F932"},
	["raised_hands"] = {unicode = "1F64C"},
	["clap"] = {unicode = "1F44F"},
	["wave"] = {unicode = "1F44B"},
	["call_me_hand"] = {unicode = "1F919"},
	["+1"] = {unicode = "1F44D"},
	["-1"] = {unicode = "1F44E"},
	["facepunch"] = {unicode = "1F44A"},
	["fist"] = {unicode = "270A"},
	["fist_left"] = {unicode = "1F91B"},
	["fist_right"] = {unicode = "1F91C"},
	["v"] = {unicode = "270C"},
	["ok_hand"] = {unicode = "1F44C"},
	["raised_hand"] = {unicode = "270B"},
	["raised_back_of_hand"] = {unicode = "1F91A"},
	["open_hands"] = {unicode = "1F450"},
	["muscle"] = {unicode = "1F4AA"},
	["pray"] = {unicode = "1F64F"},
	["foot"] = {unicode = "1F9B6"},
	["leg"] = {unicode = "1F9B5"},
	["handshake"] = {unicode = "1F91D"},
	["point_up"] = {unicode = "261D"},
	["point_up_2"] = {unicode = "1F446"},
	["point_down"] = {unicode = "1F447"},
	["point_left"] = {unicode = "1F448"},
	["point_right"] = {unicode = "1F449"},
	["fu"] = {unicode = "1F595"},
	["raised_hand_with_fingers_splayed"] = {unicode = "1F590"},
	["love_you"] = {unicode = "1F91F"},
	["metal"] = {unicode = "1F918"},
	["crossed_fingers"] = {unicode = "1F91E"},
	["vulcan_salute"] = {unicode = "1F596"},
	["writing_hand"] = {unicode = "270D"},
	["selfie"] = {unicode = "1F933"},
	["nail_care"] = {unicode = "1F485"},
	["lips"] = {unicode = "1F444"},
	["tooth"] = {unicode = "1F9B7"},
	["tongue"] = {unicode = "1F445"},
	["ear"] = {unicode = "1F442"},
	["nose"] = {unicode = "1F443"},
	["eye"] = {unicode = "1F441"},
	["eyes"] = {unicode = "1F440"},
	["brain"] = {unicode = "1F9E0"},
	["bust_in_silhouette"] = {unicode = "1F464"},
	["busts_in_silhouette"] = {unicode = "1F465"},
	["speaking_head"] = {unicode = "1F5E3"},
	["baby"] = {unicode = "1F476"},
	["child"] = {unicode = "1F9D2"},
	["boy"] = {unicode = "1F466"},
	["girl"] = {unicode = "1F467"},
	["adult"] = {unicode = "1F9D1"},
	["man"] = {unicode = "1F468"},
	["woman"] = {unicode = "1F469"},
	["blonde_woman"] = {unicode = "1F471-200D-2640"},
	["blonde_man"] = {unicode = "1F471"},
	["bearded_person"] = {unicode = "1F9D4"},
	["older_adult"] = {unicode = "1F9D3"},
	["older_man"] = {unicode = "1F474"},
	["older_woman"] = {unicode = "1F475"},
	["man_with_gua_pi_mao"] = {unicode = "1F472"},
	["woman_with_headscarf"] = {unicode = "1F9D5"},
	["woman_with_turban"] = {unicode = "1F473-200D-2640"},
	["man_with_turban"] = {unicode = "1F473"},
	["policewoman"] = {unicode = "1F46E-200D-2640"},
	["policeman"] = {unicode = "1F46E"},
	["construction_worker_woman"] = {unicode = "1F477-200D-2640"},
	["construction_worker_man"] = {unicode = "1F477"},
	["guardswoman"] = {unicode = "1F482-200D-2640"},
	["guardsman"] = {unicode = "1F482"},
	["female_detective"] = {unicode = "1F575-200D-2640"},
	["male_detective"] = {unicode = "1F575"},
	["woman_health_worker"] = {unicode = "1F469-200D-2695"},
	["man_health_worker"] = {unicode = "1F468-200D-2695"},
	["woman_farmer"] = {unicode = "1F469-200D-1F33E"},
	["man_farmer"] = {unicode = "1F468-200D-1F33E"},
	["woman_cook"] = {unicode = "1F469-200D-1F373"},
	["man_cook"] = {unicode = "1F468-200D-1F373"},
	["woman_student"] = {unicode = "1F469-200D-1F393"},
	["man_student"] = {unicode = "1F468-200D-1F393"},
	["woman_singer"] = {unicode = "1F469-200D-1F3A4"},
	["man_singer"] = {unicode = "1F468-200D-1F3A4"},
	["woman_teacher"] = {unicode = "1F469-200D-1F3EB"},
	["man_teacher"] = {unicode = "1F468-200D-1F3EB"},
	["woman_factory_worker"] = {unicode = "1F469-200D-1F3ED"},
	["man_factory_worker"] = {unicode = "1F468-200D-1F3ED"},
	["woman_technologist"] = {unicode = "1F469-200D-1F4BB"},
	["man_technologist"] = {unicode = "1F468-200D-1F4BB"},
	["woman_office_worker"] = {unicode = "1F469-200D-1F4BC"},
	["man_office_worker"] = {unicode = "1F468-200D-1F4BC"},
	["woman_mechanic"] = {unicode = "1F469-200D-1F527"},
	["man_mechanic"] = {unicode = "1F468-200D-1F527"},
	["woman_scientist"] = {unicode = "1F469-200D-1F52C"},
	["man_scientist"] = {unicode = "1F468-200D-1F52C"},
	["woman_artist"] = {unicode = "1F469-200D-1F3A8"},
	["man_artist"] = {unicode = "1F468-200D-1F3A8"},
	["woman_firefighter"] = {unicode = "1F469-200D-1F692"},
	["man_firefighter"] = {unicode = "1F468-200D-1F692"},
	["woman_pilot"] = {unicode = "1F469-200D-2708"},
	["man_pilot"] = {unicode = "1F468-200D-2708"},
	["woman_astronaut"] = {unicode = "1F469-200D-1F680"},
	["man_astronaut"] = {unicode = "1F468-200D-1F680"},
	["woman_judge"] = {unicode = "1F469-200D-2696"},
	["man_judge"] = {unicode = "1F468-200D-2696"},
	["woman_superhero"] = {unicode = "1F9B8-200D-2640"},
	["man_superhero"] = {unicode = "1F9B8-200D-2642"},
	["woman_supervillain"] = {unicode = "1F9B9-200D-2640"},
	["man_supervillain"] = {unicode = "1F9B9-200D-2642"},
	["mrs_claus"] = {unicode = "1F936"},
	["santa"] = {unicode = "1F385"},
	["sorceress"] = {unicode = "1F9D9-200D-2640"},
	["wizard"] = {unicode = "1F9D9-200D-2642"},
	["woman_elf"] = {unicode = "1F9DD-200D-2640"},
	["man_elf"] = {unicode = "1F9DD-200D-2642"},
	["woman_vampire"] = {unicode = "1F9DB-200D-2640"},
	["man_vampire"] = {unicode = "1F9DB-200D-2642"},
	["woman_zombie"] = {unicode = "1F9DF-200D-2640"},
	["man_zombie"] = {unicode = "1F9DF-200D-2642"},
	["woman_genie"] = {unicode = "1F9DE-200D-2640"},
	["man_genie"] = {unicode = "1F9DE-200D-2642"},
	["mermaid"] = {unicode = "1F9DC-200D-2640"},
	["merman"] = {unicode = "1F9DC-200D-2642"},
	["woman_fairy"] = {unicode = "1F9DA-200D-2640"},
	["man_fairy"] = {unicode = "1F9DA-200D-2642"},
	["angel"] = {unicode = "1F47C"},
	["pregnant_woman"] = {unicode = "1F930"},
	["breastfeeding"] = {unicode = "1F931"},
	["princess"] = {unicode = "1F478"},
	["prince"] = {unicode = "1F934"},
	["bride_with_veil"] = {unicode = "1F470"},
	["man_in_tuxedo"] = {unicode = "1F935"},
	["running_woman"] = {unicode = "1F3C3-200D-2640"},
	["running_man"] = {unicode = "1F3C3"},
	["walking_woman"] = {unicode = "1F6B6-200D-2640"},
	["walking_man"] = {unicode = "1F6B6"},
	["dancer"] = {unicode = "1F483"},
	["man_dancing"] = {unicode = "1F57A"},
	["dancing_women"] = {unicode = "1F46F"},
	["dancing_men"] = {unicode = "1F46F-200D-2642"},
	["couple"] = {unicode = "1F46B"},
	["two_men_holding_hands"] = {unicode = "1F46C"},
	["two_women_holding_hands"] = {unicode = "1F46D"},
	["bowing_woman"] = {unicode = "1F647-200D-2640"},
	["bowing_man"] = {unicode = "1F647"},
	["man_facepalming"] = {unicode = "1F926-200D-2642"},
	["woman_facepalming"] = {unicode = "1F926-200D-2640"},
	["woman_shrugging"] = {unicode = "1F937"},
	["man_shrugging"] = {unicode = "1F937-200D-2642"},
	["tipping_hand_woman"] = {unicode = "1F481"},
	["tipping_hand_man"] = {unicode = "1F481-200D-2642"},
	["no_good_woman"] = {unicode = "1F645"},
	["no_good_man"] = {unicode = "1F645-200D-2642"},
	["ok_woman"] = {unicode = "1F646"},
	["ok_man"] = {unicode = "1F646-200D-2642"},
	["raising_hand_woman"] = {unicode = "1F64B"},
	["raising_hand_man"] = {unicode = "1F64B-200D-2642"},
	["pouting_woman"] = {unicode = "1F64E"},
	["pouting_man"] = {unicode = "1F64E-200D-2642"},
	["frowning_woman"] = {unicode = "1F64D"},
	["frowning_man"] = {unicode = "1F64D-200D-2642"},
	["haircut_woman"] = {unicode = "1F487"},
	["haircut_man"] = {unicode = "1F487-200D-2642"},
	["massage_woman"] = {unicode = "1F486"},
	["massage_man"] = {unicode = "1F486-200D-2642"},
	["woman_in_steamy_room"] = {unicode = "1F9D6-200D-2640"},
	["man_in_steamy_room"] = {unicode = "1F9D6-200D-2642"},
	["couple_with_heart_woman_man"] = {unicode = "1F491"},
	["couple_with_heart_woman_woman"] = {unicode = "1F469-200D-2764-200D-1F469"},
	["couple_with_heart_man_man"] = {unicode = "1F468-200D-2764-200D-1F468"},
	["couplekiss_man_woman"] = {unicode = "1F48F"},
	["couplekiss_woman_woman"] = {unicode = "1F469-200D-2764-200D-1F48B-200D-1F469"},
	["couplekiss_man_man"] = {unicode = "1F468-200D-2764-200D-1F48B-200D-1F468"},
	["family_man_woman_boy"] = {unicode = "1F46A"},
	["family_man_woman_girl"] = {unicode = "1F468-200D-1F469-200D-1F467"},
	["family_man_woman_girl_boy"] = {unicode = "1F468-200D-1F469-200D-1F467-200D-1F466"},
	["family_man_woman_boy_boy"] = {unicode = "1F468-200D-1F469-200D-1F466-200D-1F466"},
	["family_man_woman_girl_girl"] = {unicode = "1F468-200D-1F469-200D-1F467-200D-1F467"},
	["family_woman_woman_boy"] = {unicode = "1F469-200D-1F469-200D-1F466"},
	["family_woman_woman_girl"] = {unicode = "1F469-200D-1F469-200D-1F467"},
	["family_woman_woman_girl_boy"] = {unicode = "1F469-200D-1F469-200D-1F467-200D-1F466"},
	["family_woman_woman_boy_boy"] = {unicode = "1F469-200D-1F469-200D-1F466-200D-1F466"},
	["family_woman_woman_girl_girl"] = {unicode = "1F469-200D-1F469-200D-1F467-200D-1F467"},
	["family_man_man_boy"] = {unicode = "1F468-200D-1F468-200D-1F466"},
	["family_man_man_girl"] = {unicode = "1F468-200D-1F468-200D-1F467"},
	["family_man_man_girl_boy"] = {unicode = "1F468-200D-1F468-200D-1F467-200D-1F466"},
	["family_man_man_boy_boy"] = {unicode = "1F468-200D-1F468-200D-1F466-200D-1F466"},
	["family_man_man_girl_girl"] = {unicode = "1F468-200D-1F468-200D-1F467-200D-1F467"},
	["family_woman_boy"] = {unicode = "1F469-200D-1F466"},
	["family_woman_girl"] = {unicode = "1F469-200D-1F467"},
	["family_woman_girl_boy"] = {unicode = "1F469-200D-1F467-200D-1F466"},
	["family_woman_boy_boy"] = {unicode = "1F469-200D-1F466-200D-1F466"},
	["family_woman_girl_girl"] = {unicode = "1F469-200D-1F467-200D-1F467"},
	["family_man_boy"] = {unicode = "1F468-200D-1F466"},
	["family_man_girl"] = {unicode = "1F468-200D-1F467"},
	["family_man_girl_boy"] = {unicode = "1F468-200D-1F467-200D-1F466"},
	["family_man_boy_boy"] = {unicode = "1F468-200D-1F466-200D-1F466"},
	["family_man_girl_girl"] = {unicode = "1F468-200D-1F467-200D-1F467"},
	["yarn"] = {unicode = "1F9F6"},
	["thread"] = {unicode = "1F9F5"},
	["coat"] = {unicode = "1F9E5"},
	["labcoat"] = {unicode = "1F97C"},
	["womans_clothes"] = {unicode = "1F45A"},
	["tshirt"] = {unicode = "1F455"},
	["jeans"] = {unicode = "1F456"},
	["necktie"] = {unicode = "1F454"},
	["dress"] = {unicode = "1F457"},
	["bikini"] = {unicode = "1F459"},
	["kimono"] = {unicode = "1F458"},
	["lipstick"] = {unicode = "1F484"},
	["kiss"] = {unicode = "1F48B"},
	["footprints"] = {unicode = "1F463"},
	["flat_shoe"] = {unicode = "1F97F"},
	["high_heel"] = {unicode = "1F460"},
	["sandal"] = {unicode = "1F461"},
	["boot"] = {unicode = "1F462"},
	["mans_shoe"] = {unicode = "1F45E"},
	["athletic_shoe"] = {unicode = "1F45F"},
	["hiking_boot"] = {unicode = "1F97E"},
	["socks"] = {unicode = "1F9E6"},
	["gloves"] = {unicode = "1F9E4"},
	["scarf"] = {unicode = "1F9E3"},
	["womans_hat"] = {unicode = "1F452"},
	["tophat"] = {unicode = "1F3A9"},
	["billed_hat"] = {unicode = "1F9E2"},
	["rescue_worker_helmet"] = {unicode = "26D1"},
	["mortar_board"] = {unicode = "1F393"},
	["crown"] = {unicode = "1F451"},
	["school_satchel"] = {unicode = "1F392"},
	["luggage"] = {unicode = "1F9F3"},
	["pouch"] = {unicode = "1F45D"},
	["purse"] = {unicode = "1F45B"},
	["handbag"] = {unicode = "1F45C"},
	["briefcase"] = {unicode = "1F4BC"},
	["eyeglasses"] = {unicode = "1F453"},
	["dark_sunglasses"] = {unicode = "1F576"},
	["goggles"] = {unicode = "1F97D"},
	["ring"] = {unicode = "1F48D"},
	["closed_umbrella"] = {unicode = "1F302"},
	["dog"] = {unicode = "1F436"},
	["cat"] = {unicode = "1F431"},
	["mouse"] = {unicode = "1F42D"},
	["hamster"] = {unicode = "1F439"},
	["rabbit"] = {unicode = "1F430"},
	["fox_face"] = {unicode = "1F98A"},
	["bear"] = {unicode = "1F43B"},
	["panda_face"] = {unicode = "1F43C"},
	["koala"] = {unicode = "1F428"},
	["tiger"] = {unicode = "1F42F"},
	["lion"] = {unicode = "1F981"},
	["cow"] = {unicode = "1F42E"},
	["pig"] = {unicode = "1F437"},
	["pig_nose"] = {unicode = "1F43D"},
	["frog"] = {unicode = "1F438"},
	["squid"] = {unicode = "1F991"},
	["octopus"] = {unicode = "1F419"},
	["shrimp"] = {unicode = "1F990"},
	["monkey_face"] = {unicode = "1F435"},
	["gorilla"] = {unicode = "1F98D"},
	["see_no_evil"] = {unicode = "1F648"},
	["hear_no_evil"] = {unicode = "1F649"},
	["speak_no_evil"] = {unicode = "1F64A"},
	["monkey"] = {unicode = "1F412"},
	["chicken"] = {unicode = "1F414"},
	["penguin"] = {unicode = "1F427"},
	["bird"] = {unicode = "1F426"},
	["baby_chick"] = {unicode = "1F424"},
	["hatching_chick"] = {unicode = "1F423"},
	["hatched_chick"] = {unicode = "1F425"},
	["duck"] = {unicode = "1F986"},
	["eagle"] = {unicode = "1F985"},
	["owl"] = {unicode = "1F989"},
	["bat"] = {unicode = "1F987"},
	["wolf"] = {unicode = "1F43A"},
	["boar"] = {unicode = "1F417"},
	["horse"] = {unicode = "1F434"},
	["unicorn"] = {unicode = "1F984"},
	["honeybee"] = {unicode = "1F41D"},
	["bug"] = {unicode = "1F41B"},
	["butterfly"] = {unicode = "1F98B"},
	["snail"] = {unicode = "1F40C"},
	["beetle"] = {unicode = "1F41E"},
	["ant"] = {unicode = "1F41C"},
	["grasshopper"] = {unicode = "1F997"},
	["spider"] = {unicode = "1F577"},
	["scorpion"] = {unicode = "1F982"},
	["crab"] = {unicode = "1F980"},
	["snake"] = {unicode = "1F40D"},
	["lizard"] = {unicode = "1F98E"},
	["t-rex"] = {unicode = "1F996"},
	["sauropod"] = {unicode = "1F995"},
	["turtle"] = {unicode = "1F422"},
	["tropical_fish"] = {unicode = "1F420"},
	["fish"] = {unicode = "1F41F"},
	["blowfish"] = {unicode = "1F421"},
	["dolphin"] = {unicode = "1F42C"},
	["shark"] = {unicode = "1F988"},
	["whale"] = {unicode = "1F433"},
	["whale2"] = {unicode = "1F40B"},
	["crocodile"] = {unicode = "1F40A"},
	["leopard"] = {unicode = "1F406"},
	["zebra"] = {unicode = "1F993"},
	["tiger2"] = {unicode = "1F405"},
	["water_buffalo"] = {unicode = "1F403"},
	["ox"] = {unicode = "1F402"},
	["cow2"] = {unicode = "1F404"},
	["deer"] = {unicode = "1F98C"},
	["dromedary_camel"] = {unicode = "1F42A"},
	["camel"] = {unicode = "1F42B"},
	["giraffe"] = {unicode = "1F992"},
	["elephant"] = {unicode = "1F418"},
	["rhinoceros"] = {unicode = "1F98F"},
	["goat"] = {unicode = "1F410"},
	["ram"] = {unicode = "1F40F"},
	["sheep"] = {unicode = "1F411"},
	["racehorse"] = {unicode = "1F40E"},
	["pig2"] = {unicode = "1F416"},
	["rat"] = {unicode = "1F400"},
	["mouse2"] = {unicode = "1F401"},
	["rooster"] = {unicode = "1F413"},
	["turkey"] = {unicode = "1F983"},
	["dove"] = {unicode = "1F54A"},
	["dog2"] = {unicode = "1F415"},
	["poodle"] = {unicode = "1F429"},
	["cat2"] = {unicode = "1F408"},
	["rabbit2"] = {unicode = "1F407"},
	["chipmunk"] = {unicode = "1F43F"},
	["hedgehog"] = {unicode = "1F994"},
	["raccoon"] = {unicode = "1F99D"},
	["llama"] = {unicode = "1F999"},
	["hippopotamus"] = {unicode = "1F99B"},
	["kangaroo"] = {unicode = "1F998"},
	["badger"] = {unicode = "1F9A1"},
	["swan"] = {unicode = "1F9A2"},
	["peacock"] = {unicode = "1F99A"},
	["parrot"] = {unicode = "1F99C"},
	["lobster"] = {unicode = "1F99E"},
	["mosquito"] = {unicode = "1F99F"},
	["paw_prints"] = {unicode = "1F43E"},
	["dragon"] = {unicode = "1F409"},
	["dragon_face"] = {unicode = "1F432"},
	["cactus"] = {unicode = "1F335"},
	["christmas_tree"] = {unicode = "1F384"},
	["evergreen_tree"] = {unicode = "1F332"},
	["deciduous_tree"] = {unicode = "1F333"},
	["palm_tree"] = {unicode = "1F334"},
	["seedling"] = {unicode = "1F331"},
	["herb"] = {unicode = "1F33F"},
	["shamrock"] = {unicode = "2618"},
	["four_leaf_clover"] = {unicode = "1F340"},
	["bamboo"] = {unicode = "1F38D"},
	["tanabata_tree"] = {unicode = "1F38B"},
	["leaves"] = {unicode = "1F343"},
	["fallen_leaf"] = {unicode = "1F342"},
	["maple_leaf"] = {unicode = "1F341"},
	["ear_of_rice"] = {unicode = "1F33E"},
	["hibiscus"] = {unicode = "1F33A"},
	["sunflower"] = {unicode = "1F33B"},
	["rose"] = {unicode = "1F339"},
	["wilted_flower"] = {unicode = "1F940"},
	["tulip"] = {unicode = "1F337"},
	["blossom"] = {unicode = "1F33C"},
	["cherry_blossom"] = {unicode = "1F338"},
	["bouquet"] = {unicode = "1F490"},
	["mushroom"] = {unicode = "1F344"},
	["chestnut"] = {unicode = "1F330"},
	["jack_o_lantern"] = {unicode = "1F383"},
	["shell"] = {unicode = "1F41A"},
	["spider_web"] = {unicode = "1F578"},
	["earth_americas"] = {unicode = "1F30E"},
	["earth_africa"] = {unicode = "1F30D"},
	["earth_asia"] = {unicode = "1F30F"},
	["full_moon"] = {unicode = "1F315"},
	["waning_gibbous_moon"] = {unicode = "1F316"},
	["last_quarter_moon"] = {unicode = "1F317"},
	["waning_crescent_moon"] = {unicode = "1F318"},
	["new_moon"] = {unicode = "1F311"},
	["waxing_crescent_moon"] = {unicode = "1F312"},
	["first_quarter_moon"] = {unicode = "1F313"},
	["waxing_gibbous_moon"] = {unicode = "1F314"},
	["new_moon_with_face"] = {unicode = "1F31A"},
	["full_moon_with_face"] = {unicode = "1F31D"},
	["first_quarter_moon_with_face"] = {unicode = "1F31B"},
	["last_quarter_moon_with_face"] = {unicode = "1F31C"},
	["sun_with_face"] = {unicode = "1F31E"},
	["crescent_moon"] = {unicode = "1F319"},
	["star"] = {unicode = "2B50"},
	["star2"] = {unicode = "1F31F"},
	["dizzy"] = {unicode = "1F4AB"},
	["sparkles"] = {unicode = "2728"},
	["comet"] = {unicode = "2604"},
	["sunny"] = {unicode = "2600"},
	["sun_behind_small_cloud"] = {unicode = "1F324"},
	["partly_sunny"] = {unicode = "26C5"},
	["sun_behind_large_cloud"] = {unicode = "1F325"},
	["sun_behind_rain_cloud"] = {unicode = "1F326"},
	["cloud"] = {unicode = "2601"},
	["cloud_with_rain"] = {unicode = "1F327"},
	["cloud_with_lightning_and_rain"] = {unicode = "26C8"},
	["cloud_with_lightning"] = {unicode = "1F329"},
	["zap"] = {unicode = "26A1"},
	["fire"] = {unicode = "1F525"},
	["boom"] = {unicode = "1F4A5"},
	["snowflake"] = {unicode = "2744"},
	["cloud_with_snow"] = {unicode = "1F328"},
	["snowman"] = {unicode = "26C4"},
	["snowman_with_snow"] = {unicode = "2603"},
	["wind_face"] = {unicode = "1F32C"},
	["dash"] = {unicode = "1F4A8"},
	["tornado"] = {unicode = "1F32A"},
	["fog"] = {unicode = "1F32B"},
	["open_umbrella"] = {unicode = "2602"},
	["umbrella"] = {unicode = "2614"},
	["droplet"] = {unicode = "1F4A7"},
	["sweat_drops"] = {unicode = "1F4A6"},
	["ocean"] = {unicode = "1F30A"},
	["green_apple"] = {unicode = "1F34F"},
	["apple"] = {unicode = "1F34E"},
	["pear"] = {unicode = "1F350"},
	["tangerine"] = {unicode = "1F34A"},
	["lemon"] = {unicode = "1F34B"},
	["banana"] = {unicode = "1F34C"},
	["watermelon"] = {unicode = "1F349"},
	["grapes"] = {unicode = "1F347"},
	["strawberry"] = {unicode = "1F353"},
	["melon"] = {unicode = "1F348"},
	["cherries"] = {unicode = "1F352"},
	["peach"] = {unicode = "1F351"},
	["pineapple"] = {unicode = "1F34D"},
	["coconut"] = {unicode = "1F965"},
	["kiwi_fruit"] = {unicode = "1F95D"},
	["mango"] = {unicode = "1F96D"},
	["avocado"] = {unicode = "1F951"},
	["broccoli"] = {unicode = "1F966"},
	["tomato"] = {unicode = "1F345"},
	["eggplant"] = {unicode = "1F346"},
	["cucumber"] = {unicode = "1F952"},
	["carrot"] = {unicode = "1F955"},
	["hot_pepper"] = {unicode = "1F336"},
	["potato"] = {unicode = "1F954"},
	["corn"] = {unicode = "1F33D"},
	["leafy_greens"] = {unicode = "1F96C"},
	["sweet_potato"] = {unicode = "1F360"},
	["peanuts"] = {unicode = "1F95C"},
	["honey_pot"] = {unicode = "1F36F"},
	["croissant"] = {unicode = "1F950"},
	["bread"] = {unicode = "1F35E"},
	["baguette_bread"] = {unicode = "1F956"},
	["bagel"] = {unicode = "1F96F"},
	["pretzel"] = {unicode = "1F968"},
	["cheese"] = {unicode = "1F9C0"},
	["egg"] = {unicode = "1F95A"},
	["bacon"] = {unicode = "1F953"},
	["steak"] = {unicode = "1F969"},
	["pancakes"] = {unicode = "1F95E"},
	["poultry_leg"] = {unicode = "1F357"},
	["meat_on_bone"] = {unicode = "1F356"},
	["bone"] = {unicode = "1F9B4"},
	["fried_shrimp"] = {unicode = "1F364"},
	["fried_egg"] = {unicode = "1F373"},
	["hamburger"] = {unicode = "1F354"},
	["fries"] = {unicode = "1F35F"},
	["stuffed_flatbread"] = {unicode = "1F959"},
	["hotdog"] = {unicode = "1F32D"},
	["pizza"] = {unicode = "1F355"},
	["sandwich"] = {unicode = "1F96A"},
	["canned_food"] = {unicode = "1F96B"},
	["spaghetti"] = {unicode = "1F35D"},
	["taco"] = {unicode = "1F32E"},
	["burrito"] = {unicode = "1F32F"},
	["green_salad"] = {unicode = "1F957"},
	["shallow_pan_of_food"] = {unicode = "1F958"},
	["ramen"] = {unicode = "1F35C"},
	["stew"] = {unicode = "1F372"},
	["fish_cake"] = {unicode = "1F365"},
	["fortune_cookie"] = {unicode = "1F960"},
	["sushi"] = {unicode = "1F363"},
	["bento"] = {unicode = "1F371"},
	["curry"] = {unicode = "1F35B"},
	["rice_ball"] = {unicode = "1F359"},
	["rice"] = {unicode = "1F35A"},
	["rice_cracker"] = {unicode = "1F358"},
	["oden"] = {unicode = "1F362"},
	["dango"] = {unicode = "1F361"},
	["shaved_ice"] = {unicode = "1F367"},
	["ice_cream"] = {unicode = "1F368"},
	["icecream"] = {unicode = "1F366"},
	["pie"] = {unicode = "1F967"},
	["cake"] = {unicode = "1F370"},
	["cupcake"] = {unicode = "1F9C1"},
	["moon_cake"] = {unicode = "1F96E"},
	["birthday"] = {unicode = "1F382"},
	["custard"] = {unicode = "1F36E"},
	["candy"] = {unicode = "1F36C"},
	["lollipop"] = {unicode = "1F36D"},
	["chocolate_bar"] = {unicode = "1F36B"},
	["popcorn"] = {unicode = "1F37F"},
	["dumpling"] = {unicode = "1F95F"},
	["doughnut"] = {unicode = "1F369"},
	["cookie"] = {unicode = "1F36A"},
	["milk_glass"] = {unicode = "1F95B"},
	["beer"] = {unicode = "1F37A"},
	["beers"] = {unicode = "1F37B"},
	["clinking_glasses"] = {unicode = "1F942"},
	["wine_glass"] = {unicode = "1F377"},
	["tumbler_glass"] = {unicode = "1F943"},
	["cocktail"] = {unicode = "1F378"},
	["tropical_drink"] = {unicode = "1F379"},
	["champagne"] = {unicode = "1F37E"},
	["sake"] = {unicode = "1F376"},
	["tea"] = {unicode = "1F375"},
	["cup_with_straw"] = {unicode = "1F964"},
	["coffee"] = {unicode = "2615"},
	["baby_bottle"] = {unicode = "1F37C"},
	["salt"] = {unicode = "1F9C2"},
	["spoon"] = {unicode = "1F944"},
	["fork_and_knife"] = {unicode = "1F374"},
	["plate_with_cutlery"] = {unicode = "1F37D"},
	["bowl_with_spoon"] = {unicode = "1F963"},
	["takeout_box"] = {unicode = "1F961"},
	["chopsticks"] = {unicode = "1F962"},
	["soccer"] = {unicode = "26BD"},
	["basketball"] = {unicode = "1F3C0"},
	["football"] = {unicode = "1F3C8"},
	["baseball"] = {unicode = "26BE"},
	["softball"] = {unicode = "1F94E"},
	["tennis"] = {unicode = "1F3BE"},
	["volleyball"] = {unicode = "1F3D0"},
	["rugby_football"] = {unicode = "1F3C9"},
	["flying_disc"] = {unicode = "1F94F"},
	["8ball"] = {unicode = "1F3B1"},
	["golf"] = {unicode = "26F3"},
	["golfing_woman"] = {unicode = "1F3CC-200D-2640"},
	["golfing_man"] = {unicode = "1F3CC"},
	["ping_pong"] = {unicode = "1F3D3"},
	["badminton"] = {unicode = "1F3F8"},
	["goal_net"] = {unicode = "1F945"},
	["ice_hockey"] = {unicode = "1F3D2"},
	["field_hockey"] = {unicode = "1F3D1"},
	["lacrosse"] = {unicode = "1F94D"},
	["cricket"] = {unicode = "1F3CF"},
	["ski"] = {unicode = "1F3BF"},
	["skier"] = {unicode = "26F7"},
	["snowboarder"] = {unicode = "1F3C2"},
	["person_fencing"] = {unicode = "1F93A"},
	["women_wrestling"] = {unicode = "1F93C-200D-2640"},
	["men_wrestling"] = {unicode = "1F93C-200D-2642"},
	["woman_cartwheeling"] = {unicode = "1F938-200D-2640"},
	["man_cartwheeling"] = {unicode = "1F938-200D-2642"},
	["woman_playing_handball"] = {unicode = "1F93E-200D-2640"},
	["man_playing_handball"] = {unicode = "1F93E-200D-2642"},
	["ice_skate"] = {unicode = "26F8"},
	["curling_stone"] = {unicode = "1F94C"},
	["skateboard"] = {unicode = "1F6F9"},
	["sled"] = {unicode = "1F6F7"},
	["bow_and_arrow"] = {unicode = "1F3F9"},
	["fishing_pole_and_fish"] = {unicode = "1F3A3"},
	["boxing_glove"] = {unicode = "1F94A"},
	["martial_arts_uniform"] = {unicode = "1F94B"},
	["rowing_woman"] = {unicode = "1F6A3-200D-2640"},
	["rowing_man"] = {unicode = "1F6A3"},
	["climbing_woman"] = {unicode = "1F9D7-200D-2640"},
	["climbing_man"] = {unicode = "1F9D7-200D-2642"},
	["swimming_woman"] = {unicode = "1F3CA-200D-2640"},
	["swimming_man"] = {unicode = "1F3CA"},
	["woman_playing_water_polo"] = {unicode = "1F93D-200D-2640"},
	["man_playing_water_polo"] = {unicode = "1F93D-200D-2642"},
	["woman_in_lotus_position"] = {unicode = "1F9D8-200D-2640"},
	["man_in_lotus_position"] = {unicode = "1F9D8-200D-2642"},
	["surfing_woman"] = {unicode = "1F3C4-200D-2640"},
	["surfing_man"] = {unicode = "1F3C4"},
	["bath"] = {unicode = "1F6C0"},
	["basketball_woman"] = {unicode = "26F9-200D-2640"},
	["basketball_man"] = {unicode = "26F9"},
	["weight_lifting_woman"] = {unicode = "1F3CB-200D-2640"},
	["weight_lifting_man"] = {unicode = "1F3CB"},
	["biking_woman"] = {unicode = "1F6B4-200D-2640"},
	["biking_man"] = {unicode = "1F6B4"},
	["mountain_biking_woman"] = {unicode = "1F6B5-200D-2640"},
	["mountain_biking_man"] = {unicode = "1F6B5"},
	["horse_racing"] = {unicode = "1F3C7"},
	["business_suit_levitating"] = {unicode = "1F574"},
	["trophy"] = {unicode = "1F3C6"},
	["running_shirt_with_sash"] = {unicode = "1F3BD"},
	["medal_sports"] = {unicode = "1F3C5"},
	["medal_military"] = {unicode = "1F396"},
	["1st_place_medal"] = {unicode = "1F947"},
	["2nd_place_medal"] = {unicode = "1F948"},
	["3rd_place_medal"] = {unicode = "1F949"},
	["reminder_ribbon"] = {unicode = "1F397"},
	["rosette"] = {unicode = "1F3F5"},
	["ticket"] = {unicode = "1F3AB"},
	["tickets"] = {unicode = "1F39F"},
	["performing_arts"] = {unicode = "1F3AD"},
	["art"] = {unicode = "1F3A8"},
	["circus_tent"] = {unicode = "1F3AA"},
	["woman_juggling"] = {unicode = "1F939-200D-2640"},
	["man_juggling"] = {unicode = "1F939-200D-2642"},
	["microphone"] = {unicode = "1F3A4"},
	["headphones"] = {unicode = "1F3A7"},
	["musical_score"] = {unicode = "1F3BC"},
	["musical_keyboard"] = {unicode = "1F3B9"},
	["drum"] = {unicode = "1F941"},
	["saxophone"] = {unicode = "1F3B7"},
	["trumpet"] = {unicode = "1F3BA"},
	["guitar"] = {unicode = "1F3B8"},
	["violin"] = {unicode = "1F3BB"},
	["clapper"] = {unicode = "1F3AC"},
	["video_game"] = {unicode = "1F3AE"},
	["space_invader"] = {unicode = "1F47E"},
	["dart"] = {unicode = "1F3AF"},
	["game_die"] = {unicode = "1F3B2"},
	["chess_pawn"] = {unicode = "265F"},
	["slot_machine"] = {unicode = "1F3B0"},
	["jigsaw"] = {unicode = "1F9E9"},
	["bowling"] = {unicode = "1F3B3"},
	["red_car"] = {unicode = "1F697"},
	["taxi"] = {unicode = "1F695"},
	["blue_car"] = {unicode = "1F699"},
	["bus"] = {unicode = "1F68C"},
	["trolleybus"] = {unicode = "1F68E"},
	["racing_car"] = {unicode = "1F3CE"},
	["police_car"] = {unicode = "1F693"},
	["ambulance"] = {unicode = "1F691"},
	["fire_engine"] = {unicode = "1F692"},
	["minibus"] = {unicode = "1F690"},
	["truck"] = {unicode = "1F69A"},
	["articulated_lorry"] = {unicode = "1F69B"},
	["tractor"] = {unicode = "1F69C"},
	["kick_scooter"] = {unicode = "1F6F4"},
	["motorcycle"] = {unicode = "1F3CD"},
	["bike"] = {unicode = "1F6B2"},
	["motor_scooter"] = {unicode = "1F6F5"},
	["rotating_light"] = {unicode = "1F6A8"},
	["oncoming_police_car"] = {unicode = "1F694"},
	["oncoming_bus"] = {unicode = "1F68D"},
	["oncoming_automobile"] = {unicode = "1F698"},
	["oncoming_taxi"] = {unicode = "1F696"},
	["aerial_tramway"] = {unicode = "1F6A1"},
	["mountain_cableway"] = {unicode = "1F6A0"},
	["suspension_railway"] = {unicode = "1F69F"},
	["railway_car"] = {unicode = "1F683"},
	["train"] = {unicode = "1F68B"},
	["monorail"] = {unicode = "1F69D"},
	["bullettrain_side"] = {unicode = "1F684"},
	["bullettrain_front"] = {unicode = "1F685"},
	["light_rail"] = {unicode = "1F688"},
	["mountain_railway"] = {unicode = "1F69E"},
	["steam_locomotive"] = {unicode = "1F682"},
	["train2"] = {unicode = "1F686"},
	["metro"] = {unicode = "1F687"},
	["tram"] = {unicode = "1F68A"},
	["station"] = {unicode = "1F689"},
	["flying_saucer"] = {unicode = "1F6F8"},
	["helicopter"] = {unicode = "1F681"},
	["small_airplane"] = {unicode = "1F6E9"},
	["airplane"] = {unicode = "2708"},
	["flight_departure"] = {unicode = "1F6EB"},
	["flight_arrival"] = {unicode = "1F6EC"},
	["sailboat"] = {unicode = "26F5"},
	["motor_boat"] = {unicode = "1F6E5"},
	["speedboat"] = {unicode = "1F6A4"},
	["ferry"] = {unicode = "26F4"},
	["passenger_ship"] = {unicode = "1F6F3"},
	["rocket"] = {unicode = "1F680"},
	["artificial_satellite"] = {unicode = "1F6F0"},
	["seat"] = {unicode = "1F4BA"},
	["canoe"] = {unicode = "1F6F6"},
	["anchor"] = {unicode = "2693"},
	["construction"] = {unicode = "1F6A7"},
	["fuelpump"] = {unicode = "26FD"},
	["busstop"] = {unicode = "1F68F"},
	["vertical_traffic_light"] = {unicode = "1F6A6"},
	["traffic_light"] = {unicode = "1F6A5"},
	["checkered_flag"] = {unicode = "1F3C1"},
	["ship"] = {unicode = "1F6A2"},
	["ferris_wheel"] = {unicode = "1F3A1"},
	["roller_coaster"] = {unicode = "1F3A2"},
	["carousel_horse"] = {unicode = "1F3A0"},
	["building_construction"] = {unicode = "1F3D7"},
	["foggy"] = {unicode = "1F301"},
	["tokyo_tower"] = {unicode = "1F5FC"},
	["factory"] = {unicode = "1F3ED"},
	["fountain"] = {unicode = "26F2"},
	["rice_scene"] = {unicode = "1F391"},
	["mountain"] = {unicode = "26F0"},
	["mountain_snow"] = {unicode = "1F3D4"},
	["mount_fuji"] = {unicode = "1F5FB"},
	["volcano"] = {unicode = "1F30B"},
	["japan"] = {unicode = "1F5FE"},
	["camping"] = {unicode = "1F3D5"},
	["tent"] = {unicode = "26FA"},
	["national_park"] = {unicode = "1F3DE"},
	["motorway"] = {unicode = "1F6E3"},
	["railway_track"] = {unicode = "1F6E4"},
	["sunrise"] = {unicode = "1F305"},
	["sunrise_over_mountains"] = {unicode = "1F304"},
	["desert"] = {unicode = "1F3DC"},
	["beach_umbrella"] = {unicode = "1F3D6"},
	["desert_island"] = {unicode = "1F3DD"},
	["city_sunrise"] = {unicode = "1F307"},
	["city_sunset"] = {unicode = "1F306"},
	["cityscape"] = {unicode = "1F3D9"},
	["night_with_stars"] = {unicode = "1F303"},
	["bridge_at_night"] = {unicode = "1F309"},
	["milky_way"] = {unicode = "1F30C"},
	["stars"] = {unicode = "1F320"},
	["sparkler"] = {unicode = "1F387"},
	["fireworks"] = {unicode = "1F386"},
	["rainbow"] = {unicode = "1F308"},
	["houses"] = {unicode = "1F3D8"},
	["european_castle"] = {unicode = "1F3F0"},
	["japanese_castle"] = {unicode = "1F3EF"},
	["stadium"] = {unicode = "1F3DF"},
	["statue_of_liberty"] = {unicode = "1F5FD"},
	["house"] = {unicode = "1F3E0"},
	["house_with_garden"] = {unicode = "1F3E1"},
	["derelict_house"] = {unicode = "1F3DA"},
	["office"] = {unicode = "1F3E2"},
	["department_store"] = {unicode = "1F3EC"},
	["post_office"] = {unicode = "1F3E3"},
	["european_post_office"] = {unicode = "1F3E4"},
	["hospital"] = {unicode = "1F3E5"},
	["bank"] = {unicode = "1F3E6"},
	["hotel"] = {unicode = "1F3E8"},
	["convenience_store"] = {unicode = "1F3EA"},
	["school"] = {unicode = "1F3EB"},
	["love_hotel"] = {unicode = "1F3E9"},
	["wedding"] = {unicode = "1F492"},
	["classical_building"] = {unicode = "1F3DB"},
	["church"] = {unicode = "26EA"},
	["mosque"] = {unicode = "1F54C"},
	["synagogue"] = {unicode = "1F54D"},
	["kaaba"] = {unicode = "1F54B"},
	["shinto_shrine"] = {unicode = "26E9"},
	["watch"] = {unicode = "231A"},
	["iphone"] = {unicode = "1F4F1"},
	["calling"] = {unicode = "1F4F2"},
	["computer"] = {unicode = "1F4BB"},
	["keyboard"] = {unicode = "2328"},
	["desktop_computer"] = {unicode = "1F5A5"},
	["printer"] = {unicode = "1F5A8"},
	["computer_mouse"] = {unicode = "1F5B1"},
	["trackball"] = {unicode = "1F5B2"},
	["joystick"] = {unicode = "1F579"},
	["clamp"] = {unicode = "1F5DC"},
	["minidisc"] = {unicode = "1F4BD"},
	["floppy_disk"] = {unicode = "1F4BE"},
	["cd"] = {unicode = "1F4BF"},
	["dvd"] = {unicode = "1F4C0"},
	["vhs"] = {unicode = "1F4FC"},
	["camera"] = {unicode = "1F4F7"},
	["camera_flash"] = {unicode = "1F4F8"},
	["video_camera"] = {unicode = "1F4F9"},
	["movie_camera"] = {unicode = "1F3A5"},
	["film_projector"] = {unicode = "1F4FD"},
	["film_strip"] = {unicode = "1F39E"},
	["telephone_receiver"] = {unicode = "1F4DE"},
	["phone"] = {unicode = "260E"},
	["pager"] = {unicode = "1F4DF"},
	["fax"] = {unicode = "1F4E0"},
	["tv"] = {unicode = "1F4FA"},
	["radio"] = {unicode = "1F4FB"},
	["studio_microphone"] = {unicode = "1F399"},
	["level_slider"] = {unicode = "1F39A"},
	["control_knobs"] = {unicode = "1F39B"},
	["compass"] = {unicode = "1F9ED"},
	["stopwatch"] = {unicode = "23F1"},
	["timer_clock"] = {unicode = "23F2"},
	["alarm_clock"] = {unicode = "23F0"},
	["mantelpiece_clock"] = {unicode = "1F570"},
	["hourglass_flowing_sand"] = {unicode = "23F3"},
	["hourglass"] = {unicode = "231B"},
	["satellite"] = {unicode = "1F4E1"},
	["battery"] = {unicode = "1F50B"},
	["electric_plug"] = {unicode = "1F50C"},
	["bulb"] = {unicode = "1F4A1"},
	["flashlight"] = {unicode = "1F526"},
	["candle"] = {unicode = "1F56F"},
	["fire_extinguisher"] = {unicode = "1F9EF"},
	["wastebasket"] = {unicode = "1F5D1"},
	["oil_drum"] = {unicode = "1F6E2"},
	["money_with_wings"] = {unicode = "1F4B8"},
	["dollar"] = {unicode = "1F4B5"},
	["yen"] = {unicode = "1F4B4"},
	["euro"] = {unicode = "1F4B6"},
	["pound"] = {unicode = "1F4B7"},
	["moneybag"] = {unicode = "1F4B0"},
	["credit_card"] = {unicode = "1F4B3"},
	["gem"] = {unicode = "1F48E"},
	["balance_scale"] = {unicode = "2696"},
	["toolbox"] = {unicode = "1F9F0"},
	["wrench"] = {unicode = "1F527"},
	["hammer"] = {unicode = "1F528"},
	["hammer_and_pick"] = {unicode = "2692"},
	["hammer_and_wrench"] = {unicode = "1F6E0"},
	["pick"] = {unicode = "26CF"},
	["nut_and_bolt"] = {unicode = "1F529"},
	["gear"] = {unicode = "2699"},
	["brick"] = {unicode = "1F9F1"},
	["chains"] = {unicode = "26D3"},
	["magnet"] = {unicode = "1F9F2"},
	["gun"] = {unicode = "1F52B"},
	["bomb"] = {unicode = "1F4A3"},
	["firecracker"] = {unicode = "1F9E8"},
	["hocho"] = {unicode = "1F52A"},
	["dagger"] = {unicode = "1F5E1"},
	["crossed_swords"] = {unicode = "2694"},
	["shield"] = {unicode = "1F6E1"},
	["smoking"] = {unicode = "1F6AC"},
	["skull_and_crossbones"] = {unicode = "2620"},
	["coffin"] = {unicode = "26B0"},
	["funeral_urn"] = {unicode = "26B1"},
	["amphora"] = {unicode = "1F3FA"},
	["crystal_ball"] = {unicode = "1F52E"},
	["prayer_beads"] = {unicode = "1F4FF"},
	["nazar_amulet"] = {unicode = "1F9FF"},
	["barber"] = {unicode = "1F488"},
	["alembic"] = {unicode = "2697"},
	["telescope"] = {unicode = "1F52D"},
	["microscope"] = {unicode = "1F52C"},
	["hole"] = {unicode = "1F573"},
	["pill"] = {unicode = "1F48A"},
	["syringe"] = {unicode = "1F489"},
	["dna"] = {unicode = "1F9EC"},
	["microbe"] = {unicode = "1F9A0"},
	["petri_dish"] = {unicode = "1F9EB"},
	["test_tube"] = {unicode = "1F9EA"},
	["thermometer"] = {unicode = "1F321"},
	["broom"] = {unicode = "1F9F9"},
	["basket"] = {unicode = "1F9FA"},
	["toilet_paper"] = {unicode = "1F9FB"},
	["label"] = {unicode = "1F3F7"},
	["bookmark"] = {unicode = "1F516"},
	["toilet"] = {unicode = "1F6BD"},
	["shower"] = {unicode = "1F6BF"},
	["bathtub"] = {unicode = "1F6C1"},
	["soap"] = {unicode = "1F9FC"},
	["sponge"] = {unicode = "1F9FD"},
	["lotion_bottle"] = {unicode = "1F9F4"},
	["key"] = {unicode = "1F511"},
	["old_key"] = {unicode = "1F5DD"},
	["couch_and_lamp"] = {unicode = "1F6CB"},
	["sleeping_bed"] = {unicode = "1F6CC"},
	["bed"] = {unicode = "1F6CF"},
	["door"] = {unicode = "1F6AA"},
	["bellhop_bell"] = {unicode = "1F6CE"},
	["teddy_bear"] = {unicode = "1F9F8"},
	["framed_picture"] = {unicode = "1F5BC"},
	["world_map"] = {unicode = "1F5FA"},
	["parasol_on_ground"] = {unicode = "26F1"},
	["moyai"] = {unicode = "1F5FF"},
	["shopping"] = {unicode = "1F6CD"},
	["shopping_cart"] = {unicode = "1F6D2"},
	["balloon"] = {unicode = "1F388"},
	["flags"] = {unicode = "1F38F"},
	["ribbon"] = {unicode = "1F380"},
	["gift"] = {unicode = "1F381"},
	["confetti_ball"] = {unicode = "1F38A"},
	["tada"] = {unicode = "1F389"},
	["dolls"] = {unicode = "1F38E"},
	["wind_chime"] = {unicode = "1F390"},
	["crossed_flags"] = {unicode = "1F38C"},
	["izakaya_lantern"] = {unicode = "1F3EE"},
	["red_envelope"] = {unicode = "1F9E7"},
	["email"] = {unicode = "2709"},
	["envelope_with_arrow"] = {unicode = "1F4E9"},
	["incoming_envelope"] = {unicode = "1F4E8"},
	["e-mail"] = {unicode = "1F4E7"},
	["love_letter"] = {unicode = "1F48C"},
	["postbox"] = {unicode = "1F4EE"},
	["mailbox_closed"] = {unicode = "1F4EA"},
	["mailbox"] = {unicode = "1F4EB"},
	["mailbox_with_mail"] = {unicode = "1F4EC"},
	["mailbox_with_no_mail"] = {unicode = "1F4ED"},
	["package"] = {unicode = "1F4E6"},
	["postal_horn"] = {unicode = "1F4EF"},
	["inbox_tray"] = {unicode = "1F4E5"},
	["outbox_tray"] = {unicode = "1F4E4"},
	["scroll"] = {unicode = "1F4DC"},
	["page_with_curl"] = {unicode = "1F4C3"},
	["bookmark_tabs"] = {unicode = "1F4D1"},
	["receipt"] = {unicode = "1F9FE"},
	["bar_chart"] = {unicode = "1F4CA"},
	["chart_with_upwards_trend"] = {unicode = "1F4C8"},
	["chart_with_downwards_trend"] = {unicode = "1F4C9"},
	["page_facing_up"] = {unicode = "1F4C4"},
	["date"] = {unicode = "1F4C5"},
	["calendar"] = {unicode = "1F4C6"},
	["spiral_calendar"] = {unicode = "1F5D3"},
	["card_index"] = {unicode = "1F4C7"},
	["card_file_box"] = {unicode = "1F5C3"},
	["ballot_box"] = {unicode = "1F5F3"},
	["file_cabinet"] = {unicode = "1F5C4"},
	["clipboard"] = {unicode = "1F4CB"},
	["spiral_notepad"] = {unicode = "1F5D2"},
	["file_folder"] = {unicode = "1F4C1"},
	["open_file_folder"] = {unicode = "1F4C2"},
	["card_index_dividers"] = {unicode = "1F5C2"},
	["newspaper_roll"] = {unicode = "1F5DE"},
	["newspaper"] = {unicode = "1F4F0"},
	["notebook"] = {unicode = "1F4D3"},
	["closed_book"] = {unicode = "1F4D5"},
	["green_book"] = {unicode = "1F4D7"},
	["blue_book"] = {unicode = "1F4D8"},
	["orange_book"] = {unicode = "1F4D9"},
	["notebook_with_decorative_cover"] = {unicode = "1F4D4"},
	["ledger"] = {unicode = "1F4D2"},
	["books"] = {unicode = "1F4DA"},
	["open_book"] = {unicode = "1F4D6"},
	["safety_pin"] = {unicode = "1F9F7"},
	["link"] = {unicode = "1F517"},
	["paperclip"] = {unicode = "1F4CE"},
	["paperclips"] = {unicode = "1F587"},
	["scissors"] = {unicode = "2702"},
	["triangular_ruler"] = {unicode = "1F4D0"},
	["straight_ruler"] = {unicode = "1F4CF"},
	["abacus"] = {unicode = "1F9EE"},
	["pushpin"] = {unicode = "1F4CC"},
	["round_pushpin"] = {unicode = "1F4CD"},
	["triangular_flag_on_post"] = {unicode = "1F6A9"},
	["white_flag"] = {unicode = "1F3F3"},
	["black_flag"] = {unicode = "1F3F4"},
	["rainbow_flag"] = {unicode = "1F3F3-200D-1F308"},
	["closed_lock_with_key"] = {unicode = "1F510"},
	["lock"] = {unicode = "1F512"},
	["unlock"] = {unicode = "1F513"},
	["lock_with_ink_pen"] = {unicode = "1F50F"},
	["pen"] = {unicode = "1F58A"},
	["fountain_pen"] = {unicode = "1F58B"},
	["black_nib"] = {unicode = "2712"},
	["memo"] = {unicode = "1F4DD"},
	["pencil2"] = {unicode = "270F"},
	["crayon"] = {unicode = "1F58D"},
	["paintbrush"] = {unicode = "1F58C"},
	["mag"] = {unicode = "1F50D"},
	["mag_right"] = {unicode = "1F50E"},
	["heart"] = {unicode = "2764"},
	["orange_heart"] = {unicode = "1F9E1"},
	["yellow_heart"] = {unicode = "1F49B"},
	["green_heart"] = {unicode = "1F49A"},
	["blue_heart"] = {unicode = "1F499"},
	["purple_heart"] = {unicode = "1F49C"},
	["black_heart"] = {unicode = "1F5A4"},
	["broken_heart"] = {unicode = "1F494"},
	["heavy_heart_exclamation"] = {unicode = "2763"},
	["two_hearts"] = {unicode = "1F495"},
	["revolving_hearts"] = {unicode = "1F49E"},
	["heartbeat"] = {unicode = "1F493"},
	["heartpulse"] = {unicode = "1F497"},
	["sparkling_heart"] = {unicode = "1F496"},
	["cupid"] = {unicode = "1F498"},
	["gift_heart"] = {unicode = "1F49D"},
	["heart_decoration"] = {unicode = "1F49F"},
	["peace_symbol"] = {unicode = "262E"},
	["latin_cross"] = {unicode = "271D"},
	["star_and_crescent"] = {unicode = "262A"},
	["om"] = {unicode = "1F549"},
	["wheel_of_dharma"] = {unicode = "2638"},
	["star_of_david"] = {unicode = "2721"},
	["six_pointed_star"] = {unicode = "1F52F"},
	["menorah"] = {unicode = "1F54E"},
	["yin_yang"] = {unicode = "262F"},
	["orthodox_cross"] = {unicode = "2626"},
	["place_of_worship"] = {unicode = "1F6D0"},
	["ophiuchus"] = {unicode = "26CE"},
	["aries"] = {unicode = "2648"},
	["taurus"] = {unicode = "2649"},
	["gemini"] = {unicode = "264A"},
	["cancer"] = {unicode = "264B"},
	["leo"] = {unicode = "264C"},
	["virgo"] = {unicode = "264D"},
	["libra"] = {unicode = "264E"},
	["scorpius"] = {unicode = "264F"},
	["sagittarius"] = {unicode = "2650"},
	["capricorn"] = {unicode = "2651"},
	["aquarius"] = {unicode = "2652"},
	["pisces"] = {unicode = "2653"},
	["id"] = {unicode = "1F194"},
	["atom_symbol"] = {unicode = "269B"},
	["u7a7a"] = {unicode = "1F233"},
	["u5272"] = {unicode = "1F239"},
	["radioactive"] = {unicode = "2622"},
	["biohazard"] = {unicode = "2623"},
	["mobile_phone_off"] = {unicode = "1F4F4"},
	["vibration_mode"] = {unicode = "1F4F3"},
	["u6709"] = {unicode = "1F236"},
	["u7121"] = {unicode = "1F21A"},
	["u7533"] = {unicode = "1F238"},
	["u55b6"] = {unicode = "1F23A"},
	["u6708"] = {unicode = "1F237"},
	["eight_pointed_black_star"] = {unicode = "2734"},
	["vs"] = {unicode = "1F19A"},
	["accept"] = {unicode = "1F251"},
	["white_flower"] = {unicode = "1F4AE"},
	["ideograph_advantage"] = {unicode = "1F250"},
	["secret"] = {unicode = "3299"},
	["congratulations"] = {unicode = "3297"},
	["u5408"] = {unicode = "1F234"},
	["u6e80"] = {unicode = "1F235"},
	["u7981"] = {unicode = "1F232"},
	["a"] = {unicode = "1F170"},
	["b"] = {unicode = "1F171"},
	["ab"] = {unicode = "1F18E"},
	["cl"] = {unicode = "1F191"},
	["o2"] = {unicode = "1F17E"},
	["sos"] = {unicode = "1F198"},
	["no_entry"] = {unicode = "26D4"},
	["name_badge"] = {unicode = "1F4DB"},
	["no_entry_sign"] = {unicode = "1F6AB"},
	["x"] = {unicode = "274C"},
	["o"] = {unicode = "2B55"},
	["stop_sign"] = {unicode = "1F6D1"},
	["anger"] = {unicode = "1F4A2"},
	["hotsprings"] = {unicode = "2668"},
	["no_pedestrians"] = {unicode = "1F6B7"},
	["do_not_litter"] = {unicode = "1F6AF"},
	["no_bicycles"] = {unicode = "1F6B3"},
	["non-potable_water"] = {unicode = "1F6B1"},
	["underage"] = {unicode = "1F51E"},
	["no_mobile_phones"] = {unicode = "1F4F5"},
	["exclamation"] = {unicode = "2757"},
	["grey_exclamation"] = {unicode = "2755"},
	["question"] = {unicode = "2753"},
	["grey_question"] = {unicode = "2754"},
	["bangbang"] = {unicode = "203C"},
	["interrobang"] = {unicode = "2049"},
	["low_brightness"] = {unicode = "1F505"},
	["high_brightness"] = {unicode = "1F506"},
	["trident"] = {unicode = "1F531"},
	["fleur_de_lis"] = {unicode = "269C"},
	["part_alternation_mark"] = {unicode = "303D"},
	["warning"] = {unicode = "26A0"},
	["children_crossing"] = {unicode = "1F6B8"},
	["beginner"] = {unicode = "1F530"},
	["recycle"] = {unicode = "267B"},
	["u6307"] = {unicode = "1F22F"},
	["chart"] = {unicode = "1F4B9"},
	["sparkle"] = {unicode = "2747"},
	["eight_spoked_asterisk"] = {unicode = "2733"},
	["negative_squared_cross_mark"] = {unicode = "274E"},
	["white_check_mark"] = {unicode = "2705"},
	["diamond_shape_with_a_dot_inside"] = {unicode = "1F4A0"},
	["cyclone"] = {unicode = "1F300"},
	["loop"] = {unicode = "27BF"},
	["globe_with_meridians"] = {unicode = "1F310"},
	["m"] = {unicode = "24C2"},
	["atm"] = {unicode = "1F3E7"},
	["sa"] = {unicode = "1F202"},
	["passport_control"] = {unicode = "1F6C2"},
	["customs"] = {unicode = "1F6C3"},
	["baggage_claim"] = {unicode = "1F6C4"},
	["left_luggage"] = {unicode = "1F6C5"},
	["wheelchair"] = {unicode = "267F"},
	["no_smoking"] = {unicode = "1F6AD"},
	["wc"] = {unicode = "1F6BE"},
	["parking"] = {unicode = "1F17F"},
	["potable_water"] = {unicode = "1F6B0"},
	["mens"] = {unicode = "1F6B9"},
	["womens"] = {unicode = "1F6BA"},
	["baby_symbol"] = {unicode = "1F6BC"},
	["restroom"] = {unicode = "1F6BB"},
	["put_litter_in_its_place"] = {unicode = "1F6AE"},
	["cinema"] = {unicode = "1F3A6"},
	["signal_strength"] = {unicode = "1F4F6"},
	["koko"] = {unicode = "1F201"},
	["ng"] = {unicode = "1F196"},
	["ok"] = {unicode = "1F197"},
	["up"] = {unicode = "1F199"},
	["cool"] = {unicode = "1F192"},
	["new"] = {unicode = "1F195"},
	["free"] = {unicode = "1F193"},
	["zero"] = {unicode = "30-20E3"},
	["one"] = {unicode = "31-20E3"},
	["two"] = {unicode = "32-20E3"},
	["three"] = {unicode = "33-20E3"},
	["four"] = {unicode = "34-20E3"},
	["five"] = {unicode = "35-20E3"},
	["six"] = {unicode = "36-20E3"},
	["seven"] = {unicode = "37-20E3"},
	["eight"] = {unicode = "38-20E3"},
	["nine"] = {unicode = "39-20E3"},
	["keycap_ten"] = {unicode = "1F51F"},
	["asterisk"] = {unicode = "2A-20E3"},
	["eject_button"] = {unicode = "23CF"},
	["arrow_forward"] = {unicode = "25B6"},
	["pause_button"] = {unicode = "23F8"},
	["next_track_button"] = {unicode = "23ED"},
	["stop_button"] = {unicode = "23F9"},
	["record_button"] = {unicode = "23FA"},
	["play_or_pause_button"] = {unicode = "23EF"},
	["previous_track_button"] = {unicode = "23EE"},
	["fast_forward"] = {unicode = "23E9"},
	["rewind"] = {unicode = "23EA"},
	["twisted_rightwards_arrows"] = {unicode = "1F500"},
	["repeat"] = {unicode = "1F501"},
	["repeat_one"] = {unicode = "1F502"},
	["arrow_backward"] = {unicode = "25C0"},
	["arrow_up_small"] = {unicode = "1F53C"},
	["arrow_down_small"] = {unicode = "1F53D"},
	["arrow_double_up"] = {unicode = "23EB"},
	["arrow_double_down"] = {unicode = "23EC"},
	["arrow_right"] = {unicode = "27A1"},
	["arrow_left"] = {unicode = "2B05"},
	["arrow_up"] = {unicode = "2B06"},
	["arrow_down"] = {unicode = "2B07"},
	["arrow_upper_right"] = {unicode = "2197"},
	["arrow_lower_right"] = {unicode = "2198"},
	["arrow_lower_left"] = {unicode = "2199"},
	["arrow_upper_left"] = {unicode = "2196"},
	["arrow_up_down"] = {unicode = "2195"},
	["left_right_arrow"] = {unicode = "2194"},
	["arrows_counterclockwise"] = {unicode = "1F504"},
	["arrow_right_hook"] = {unicode = "21AA"},
	["leftwards_arrow_with_hook"] = {unicode = "21A9"},
	["arrow_heading_up"] = {unicode = "2934"},
	["arrow_heading_down"] = {unicode = "2935"},
	["hash"] = {unicode = "23-20E3"},
	["information_source"] = {unicode = "2139"},
	["abc"] = {unicode = "1F524"},
	["abcd"] = {unicode = "1F521"},
	["capital_abcd"] = {unicode = "1F520"},
	["symbols"] = {unicode = "1F523"},
	["musical_note"] = {unicode = "1F3B5"},
	["notes"] = {unicode = "1F3B6"},
	["wavy_dash"] = {unicode = "3030"},
	["curly_loop"] = {unicode = "27B0"},
	["heavy_check_mark"] = {unicode = "2714"},
	["arrows_clockwise"] = {unicode = "1F503"},
	["heavy_plus_sign"] = {unicode = "2795"},
	["heavy_minus_sign"] = {unicode = "2796"},
	["heavy_division_sign"] = {unicode = "2797"},
	["heavy_multiplication_x"] = {unicode = "2716"},
	["infinity"] = {unicode = "267E"},
	["heavy_dollar_sign"] = {unicode = "1F4B2"},
	["currency_exchange"] = {unicode = "1F4B1"},
	["copyright"] = {unicode = "A9"},
	["registered"] = {unicode = "AE"},
	["tm"] = {unicode = "2122"},
	["end"] = {unicode = "1F51A"},
	["back"] = {unicode = "1F519"},
	["on"] = {unicode = "1F51B"},
	["top"] = {unicode = "1F51D"},
	["soon"] = {unicode = "1F51C"},
	["ballot_box_with_check"] = {unicode = "2611"},
	["radio_button"] = {unicode = "1F518"},
	["white_circle"] = {unicode = "26AA"},
	["black_circle"] = {unicode = "26AB"},
	["red_circle"] = {unicode = "1F534"},
	["large_blue_circle"] = {unicode = "1F535"},
	["small_orange_diamond"] = {unicode = "1F538"},
	["small_blue_diamond"] = {unicode = "1F539"},
	["large_orange_diamond"] = {unicode = "1F536"},
	["large_blue_diamond"] = {unicode = "1F537"},
	["small_red_triangle"] = {unicode = "1F53A"},
	["black_small_square"] = {unicode = "25AA"},
	["white_small_square"] = {unicode = "25AB"},
	["black_large_square"] = {unicode = "2B1B"},
	["white_large_square"] = {unicode = "2B1C"},
	["small_red_triangle_down"] = {unicode = "1F53B"},
	["black_medium_square"] = {unicode = "25FC"},
	["white_medium_square"] = {unicode = "25FB"},
	["black_medium_small_square"] = {unicode = "25FE"},
	["white_medium_small_square"] = {unicode = "25FD"},
	["black_square_button"] = {unicode = "1F532"},
	["white_square_button"] = {unicode = "1F533"},
	["speaker"] = {unicode = "1F508"},
	["sound"] = {unicode = "1F509"},
	["loud_sound"] = {unicode = "1F50A"},
	["mute"] = {unicode = "1F507"},
	["mega"] = {unicode = "1F4E3"},
	["loudspeaker"] = {unicode = "1F4E2"},
	["bell"] = {unicode = "1F514"},
	["no_bell"] = {unicode = "1F515"},
	["black_joker"] = {unicode = "1F0CF"},
	["mahjong"] = {unicode = "1F004"},
	["spades"] = {unicode = "2660"},
	["clubs"] = {unicode = "2663"},
	["hearts"] = {unicode = "2665"},
	["diamonds"] = {unicode = "2666"},
	["flower_playing_cards"] = {unicode = "1F3B4"},
	["thought_balloon"] = {unicode = "1F4AD"},
	["right_anger_bubble"] = {unicode = "1F5EF"},
	["speech_balloon"] = {unicode = "1F4AC"},
	["left_speech_bubble"] = {unicode = "1F5E8"},
	["clock1"] = {unicode = "1F550"},
	["clock2"] = {unicode = "1F551"},
	["clock3"] = {unicode = "1F552"},
	["clock4"] = {unicode = "1F553"},
	["clock5"] = {unicode = "1F554"},
	["clock6"] = {unicode = "1F555"},
	["clock7"] = {unicode = "1F556"},
	["clock8"] = {unicode = "1F557"},
	["clock9"] = {unicode = "1F558"},
	["clock10"] = {unicode = "1F559"},
	["clock11"] = {unicode = "1F55A"},
	["clock12"] = {unicode = "1F55B"},
	["clock130"] = {unicode = "1F55C"},
	["clock230"] = {unicode = "1F55D"},
	["clock330"] = {unicode = "1F55E"},
	["clock430"] = {unicode = "1F55F"},
	["clock530"] = {unicode = "1F560"},
	["clock630"] = {unicode = "1F561"},
	["clock730"] = {unicode = "1F562"},
	["clock830"] = {unicode = "1F563"},
	["clock930"] = {unicode = "1F564"},
	["clock1030"] = {unicode = "1F565"},
	["clock1130"] = {unicode = "1F566"},
	["clock1230"] = {unicode = "1F567"},
	["pirate_flag"] = {unicode = "1F3F4-200D-2620"},
	
	-- Country flags
	["flag_af"] = {unicode = "1F1E6-1F1EB"},						-- Afghanistan
	["flag_ax"] = {unicode = "1F1E6-1F1FD"},						-- Aland Islands
	["flag_al"] = {unicode = "1F1E6-1F1F1"},						-- Albania
	["flag_dz"] = {unicode = "1F1E9-1F1FF"},						-- Algeria
	["flag_as"] = {unicode = "1F1E6-1F1F8"},						-- American Samoa
	["flag_ad"] = {unicode = "1F1E6-1F1E9"},						-- Andorra
	["flag_ao"] = {unicode = "1F1E6-1F1F4"},						-- Angola
	["flag_ai"] = {unicode = "1F1E6-1F1EE"},						-- Anguilla
	["flag_aq"] = {unicode = "1F1E6-1F1F6"},						-- Antarctica
	["flag_ag"] = {unicode = "1F1E6-1F1EC"},						-- Antigua and Barbuda
	["flag_ar"] = {unicode = "1F1E6-1F1F7"},						-- Argentina
	["flag_am"] = {unicode = "1F1E6-1F1F2"},						-- Armenia
	["flag_aw"] = {unicode = "1F1E6-1F1FC"},						-- Aruba
	["flag_au"] = {unicode = "1F1E6-1F1FA"},						-- Australia
	["flag_at"] = {unicode = "1F1E6-1F1F9"},						-- Austria
	["flag_az"] = {unicode = "1F1E6-1F1FF"},						-- Azerbaijan
	["flag_bs"] = {unicode = "1F1E7-1F1F8"},						-- Bahamas
	["flag_bh"] = {unicode = "1F1E7-1F1ED"},						-- Bahrain
	["flag_bd"] = {unicode = "1F1E7-1F1E9"},						-- Bangladesh
	["flag_bb"] = {unicode = "1F1E7-1F1E7"},						-- Barbados
	["flag_by"] = {unicode = "1F1E7-1F1FE"},						-- Belarus
	["flag_be"] = {unicode = "1F1E7-1F1EA"},						-- Belgium
	["flag_bz"] = {unicode = "1F1E7-1F1FF"},						-- Belize
	["flag_bj"] = {unicode = "1F1E7-1F1EF"},						-- Benin
	["flag_bm"] = {unicode = "1F1E7-1F1F2"},						-- Bermuda
	["flag_bt"] = {unicode = "1F1E7-1F1F9"},						-- Bhutan
	["flag_bo"] = {unicode = "1F1E7-1F1F4"},						-- Bolivia
	["flag_bq"] = {unicode = "1F1E7-1F1F6"},						-- Caribbean Netherlands
	["flag_ba"] = {unicode = "1F1E7-1F1E6"},						-- Bosnia Herzegovina
	["flag_bw"] = {unicode = "1F1E7-1F1FC"},						-- Botswana
	["flag_br"] = {unicode = "1F1E7-1F1F7"},						-- Brazil
	["flag_io"] = {unicode = "1F1EE-1F1F4"},						-- British Indian Ocean Territory
	["flag_vg"] = {unicode = "1F1FB-1F1EC"},						-- British Virgin Islands
	["flag_bn"] = {unicode = "1F1E7-1F1F3"},						-- Brunei
	["flag_bg"] = {unicode = "1F1E7-1F1EC"},						-- Bulgaria
	["flag_bf"] = {unicode = "1F1E7-1F1EB"},						-- Burkina Faso
	["flag_bi"] = {unicode = "1F1E7-1F1EE"},						-- Burundi
	["flag_cv"] = {unicode = "1F1E8-1F1FB"},						-- Cape Verde
	["flag_kh"] = {unicode = "1F1F0-1F1ED"},						-- Cambodia
	["flag_cm"] = {unicode = "1F1E8-1F1F2"},						-- Cameroon
	["flag_ca"] = {unicode = "1F1E8-1F1E6"},						-- Canada
	["flag_ic"] = {unicode = "1F1EE-1F1E8"},						-- Canary Islands
	["flag_ky"] = {unicode = "1F1F0-1F1FE"},						-- Cayman Islands
	["flag_cf"] = {unicode = "1F1E8-1F1EB"},						-- Central African Republic
	["flag_td"] = {unicode = "1F1F9-1F1E9"},						-- Chad
	["flag_cl"] = {unicode = "1F1E8-1F1F1"},						-- Chile
	["flag_cn"] = {unicode = "1F1E8-1F1F3"},						-- China
	["flag_cx"] = {unicode = "1F1E8-1F1FD"},						-- Christmas Island
	["flag_cc"] = {unicode = "1F1E8-1F1E8"},						-- Cocos Islands
	["flag_co"] = {unicode = "1F1E8-1F1F4"},						-- Colombia
	["flag_km"] = {unicode = "1F1F0-1F1F2"},						-- Comoros
	["flag_cg"] = {unicode = "1F1E8-1F1EC"},						-- Congo Brazzaville
	["flag_cd"] = {unicode = "1F1E8-1F1E9"},						-- Congo Kinshasa
	["flag_ck"] = {unicode = "1F1E8-1F1F0"},						-- Cook Islands
	["flag_cr"] = {unicode = "1F1E8-1F1F7"},						-- Costa Rica
	["flag_hr"] = {unicode = "1F1ED-1F1F7"},						-- Croatia
	["flag_cu"] = {unicode = "1F1E8-1F1FA"},						-- Cuba
	["flag_cw"] = {unicode = "1F1E8-1F1FC"},						-- Curacao
	["flag_cy"] = {unicode = "1F1E8-1F1FE"},						-- Cyprus
	["flag_cz"] = {unicode = "1F1E8-1F1FF"},						-- Czech Republic
	["flag_dk"] = {unicode = "1F1E9-1F1F0"},						-- Denmark
	["flag_dj"] = {unicode = "1F1E9-1F1EF"},						-- Djibouti
	["flag_dm"] = {unicode = "1F1E9-1F1F2"},						-- Dominica
	["flag_do"] = {unicode = "1F1E9-1F1F4"},						-- Dominican Republic
	["flag_ec"] = {unicode = "1F1EA-1F1E8"},						-- Ecuador
	["flag_eg"] = {unicode = "1F1EA-1F1EC"},						-- Egypt
	["flag_sv"] = {unicode = "1F1F8-1F1FB"},						-- El Salvador
	["flag_gq"] = {unicode = "1F1EC-1F1F6"},						-- Equatorial Guinea
	["flag_er"] = {unicode = "1F1EA-1F1F7"},						-- Eritrea
	["flag_ee"] = {unicode = "1F1EA-1F1EA"},						-- Estonia
	["flag_et"] = {unicode = "1F1EA-1F1F9"},						-- Ethiopia
	["flag_eu"] = {unicode = "1F1EA-1F1FA"},						-- European Union
	["flag_fk"] = {unicode = "1F1EB-1F1F0"},						-- Falkland Islands
	["flag_fo"] = {unicode = "1F1EB-1F1F4"},						-- Faroe Islands
	["flag_fj"] = {unicode = "1F1EB-1F1EF"},						-- Fiji
	["flag_fi"] = {unicode = "1F1EB-1F1EE"},						-- Finland
	["flag_fr"] = {unicode = "1F1EB-1F1F7"},						-- France
	["flag_gf"] = {unicode = "1F1EC-1F1EB"},						-- French Guiana
	["flag_pf"] = {unicode = "1F1F5-1F1EB"},						-- French Polynesia
	["flag_tf"] = {unicode = "1F1F9-1F1EB"},						-- French Southern Territories
	["flag_ga"] = {unicode = "1F1EC-1F1E6"},						-- Gabon
	["flag_gm"] = {unicode = "1F1EC-1F1F2"},						-- Gambia
	["flag_ge"] = {unicode = "1F1EC-1F1EA"},						-- Georgia
	["flag_de"] = {unicode = "1F1E9-1F1EA"},						-- Germany
	["flag_gh"] = {unicode = "1F1EC-1F1ED"},						-- Ghana
	["flag_gi"] = {unicode = "1F1EC-1F1EE"},						-- Gibraltar
	["flag_gr"] = {unicode = "1F1EC-1F1F7"},						-- Greece
	["flag_gl"] = {unicode = "1F1EC-1F1F1"},						-- Greenland
	["flag_gd"] = {unicode = "1F1EC-1F1E9"},						-- Grenada
	["flag_gp"] = {unicode = "1F1EC-1F1F5"},						-- Guadeloupe
	["flag_gu"] = {unicode = "1F1EC-1F1FA"},						-- Guam
	["flag_gt"] = {unicode = "1F1EC-1F1F9"},						-- Guatemala
	["flag_gg"] = {unicode = "1F1EC-1F1EC"},						-- Guernsey
	["flag_gn"] = {unicode = "1F1EC-1F1F3"},						-- Guinea
	["flag_gw"] = {unicode = "1F1EC-1F1FC"},						-- Guinea Bissau
	["flag_gy"] = {unicode = "1F1EC-1F1FE"},						-- Guyana
	["flag_ht"] = {unicode = "1F1ED-1F1F9"},						-- Haiti
	["flag_hn"] = {unicode = "1F1ED-1F1F3"},						-- Honduras
	["flag_hk"] = {unicode = "1F1ED-1F1F0"},						-- Hong Kong
	["flag_hu"] = {unicode = "1F1ED-1F1FA"},						-- Hungary
	["flag_is"] = {unicode = "1F1EE-1F1F8"},						-- Iceland
	["flag_in"] = {unicode = "1F1EE-1F1F3"},						-- India
	["flag_id"] = {unicode = "1F1EE-1F1E9"},						-- Indonesia
	["flag_ir"] = {unicode = "1F1EE-1F1F7"},						-- Iran
	["flag_iq"] = {unicode = "1F1EE-1F1F6"},						-- Iraq
	["flag_ie"] = {unicode = "1F1EE-1F1EA"},						-- Ireland
	["flag_im"] = {unicode = "1F1EE-1F1F2"},						-- Isle of Man
	["flag_il"] = {unicode = "1F1EE-1F1F1"},						-- Israel
	["flag_it"] = {unicode = "1F1EE-1F1F9"},						-- Italy
	["flag_ci"] = {unicode = "1F1E8-1F1EE"},						-- Cote d'Ivoire
	["flag_jm"] = {unicode = "1F1EF-1F1F2"},						-- Jamaica
	["flag_jp"] = {unicode = "1F1EF-1F1F5"},						-- Japan
	["flag_je"] = {unicode = "1F1EF-1F1EA"},						-- Jersey
	["flag_jo"] = {unicode = "1F1EF-1F1F4"},						-- Jordan
	["flag_kz"] = {unicode = "1F1F0-1F1FF"},						-- Kazakhstan
	["flag_ke"] = {unicode = "1F1F0-1F1EA"},						-- Kenya
	["flag_ki"] = {unicode = "1F1F0-1F1EE"},						-- Kiribati
	["flag_kx"] = {unicode = "1F1FD-1F1F0"},						-- Kosovo
	["flag_kw"] = {unicode = "1F1F0-1F1FC"},						-- Kuwait
	["flag_kg"] = {unicode = "1F1F0-1F1EC"},						-- Kyrgyzstan
	["flag_la"] = {unicode = "1F1F1-1F1E6"},						-- Laos
	["flag_lv"] = {unicode = "1F1F1-1F1FB"},						-- Latvia
	["flag_lb"] = {unicode = "1F1F1-1F1E7"},						-- Lebanon
	["flag_ls"] = {unicode = "1F1F1-1F1F8"},						-- Lesotho
	["flag_lr"] = {unicode = "1F1F1-1F1F7"},						-- Liberia
	["flag_ly"] = {unicode = "1F1F1-1F1FE"},						-- Libya
	["flag_li"] = {unicode = "1F1F1-1F1EE"},						-- Liechtenstein
	["flag_lt"] = {unicode = "1F1F1-1F1F9"},						-- Lithuania
	["flag_lu"] = {unicode = "1F1F1-1F1FA"},						-- Luxembourg
	["flag_mo"] = {unicode = "1F1F2-1F1F4"},						-- Macau
	["flag_mk"] = {unicode = "1F1F2-1F1F0"},						-- Macedonia
	["flag_mg"] = {unicode = "1F1F2-1F1EC"},						-- Madagascar
	["flag_mw"] = {unicode = "1F1F2-1F1FC"},						-- Malawi
	["flag_my"] = {unicode = "1F1F2-1F1FE"},						-- Malaysia
	["flag_mv"] = {unicode = "1F1F2-1F1FB"},						-- Maldives
	["flag_ml"] = {unicode = "1F1F2-1F1F1"},						-- Mali
	["flag_mt"] = {unicode = "1F1F2-1F1F9"},						-- Malta
	["flag_mh"] = {unicode = "1F1F2-1F1ED"},						-- Marshall Islands
	["flag_mq"] = {unicode = "1F1F2-1F1F6"},						-- Martinique
	["flag_mr"] = {unicode = "1F1F2-1F1F7"},						-- Mauritania
	["flag_mu"] = {unicode = "1F1F2-1F1FA"},						-- Mauritius
	["flag_yt"] = {unicode = "1F1FE-1F1F9"},						-- Mayottte
	["flag_mx"] = {unicode = "1F1F2-1F1FD"},						-- Mexico
	["flag_fm"] = {unicode = "1F1EB-1F1F2"},						-- Micronesia
	["flag_md"] = {unicode = "1F1F2-1F1E9"},						-- Moldova
	["flag_mc"] = {unicode = "1F1F2-1F1E8"},						-- Monaco
	["flag_mn"] = {unicode = "1F1F2-1F1F3"},						-- Mongolia
	["flag_me"] = {unicode = "1F1F2-1F1EA"},						-- Montenegro
	["flag_ms"] = {unicode = "1F1F2-1F1F8"},						-- Montserrat
	["flag_ma"] = {unicode = "1F1F2-1F1E6"},						-- Morocco
	["flag_mz"] = {unicode = "1F1F2-1F1FF"},						-- Mozambique
	["flag_mm"] = {unicode = "1F1F2-1F1F2"},						-- Myanmar
	["flag_na"] = {unicode = "1F1F3-1F1E6"},						-- Namibia
	["flag_nr"] = {unicode = "1F1F3-1F1F7"},						-- Nauru
	["flag_np"] = {unicode = "1F1F3-1F1F5"},						-- Nepal
	["flag_nl"] = {unicode = "1F1F3-1F1F1"},						-- Netherlands
	["flag_nc"] = {unicode = "1F1F3-1F1E8"},						-- New Caledonia
	["flag_nz"] = {unicode = "1F1F3-1F1FF"},						-- New Zealand
	["flag_ni"] = {unicode = "1F1F3-1F1EE"},						-- Nicaragua
	["flag_ne"] = {unicode = "1F1F3-1F1EA"},						-- Niger
	["flag_ng"] = {unicode = "1F1F3-1F1EC"},						-- Nigeria
	["flag_nu"] = {unicode = "1F1F3-1F1FA"},						-- Niue
	["flag_nf"] = {unicode = "1F1F3-1F1EB"},						-- Norfolk Island
	["flag_mp"] = {unicode = "1F1F2-1F1F5"},						-- Northern Mariana Islands
	["flag_kp"] = {unicode = "1F1F0-1F1F5"},						-- North Korea
	["flag_no"] = {unicode = "1F1F3-1F1F4"},						-- Norway
	["flag_om"] = {unicode = "1F1F4-1F1F2"},						-- Oman
	["flag_pk"] = {unicode = "1F1F5-1F1F0"},						-- Pakistan
	["flag_pw"] = {unicode = "1F1F5-1F1FC"},						-- Palau
	["flag_ps"] = {unicode = "1F1F5-1F1F8"},						-- Palestinian Territories
	["flag_pa"] = {unicode = "1F1F5-1F1E6"},						-- Panama
	["flag_pg"] = {unicode = "1F1F5-1F1EC"},						-- Papua New Guinea
	["flag_py"] = {unicode = "1F1F5-1F1FE"},						-- Paraguay
	["flag_pe"] = {unicode = "1F1F5-1F1EA"},						-- Peru
	["flag_ph"] = {unicode = "1F1F5-1F1ED"},						-- Philippines
	["flag_pn"] = {unicode = "1F1F5-1F1F3"},						-- Pitcairn Islands
	["flag_pl"] = {unicode = "1F1F5-1F1F1"},						-- Poland
	["flag_pt"] = {unicode = "1F1F5-1F1F9"},						-- Portugal
	["flag_pr"] = {unicode = "1F1F5-1F1F7"},						-- Puerto Rico
	["flag_qa"] = {unicode = "1F1F6-1F1E6"},						-- Qatar
	["flag_re"] = {unicode = "1F1F7-1F1EA"},						-- Reunion
	["flag_ro"] = {unicode = "1F1F7-1F1F4"},						-- Romania
	["flag_ru"] = {unicode = "1F1F7-1F1FA"},						-- Russia
	["flag_rw"] = {unicode = "1F1F7-1F1FC"},						-- Rwanda
	["flag_bl"] = {unicode = "1F1E7-1F1F1"},						-- St Barthelemy
	["flag_sh"] = {unicode = "1F1F8-1F1ED"},						-- St Helena
	["flag_kn"] = {unicode = "1F1F0-1F1F3"},						-- St Kitts and Nevis
	["flag_lc"] = {unicode = "1F1F1-1F1E8"},						-- St Lucia
	["flag_pm"] = {unicode = "1F1F5-1F1F2"},						-- St Pierre and Miquelon
	["flag_vc"] = {unicode = "1F1FB-1F1E8"},						-- St Vicent and the Grenadines
	["flag_ws"] = {unicode = "1F1FC-1F1F8"},						-- Samoa
	["flag_sm"] = {unicode = "1F1F8-1F1F2"},						-- San Marino
	["flag_st"] = {unicode = "1F1F8-1F1F9"},						-- Sao Tome e Principe
	["flag_sa"] = {unicode = "1F1F8-1F1E6"},						-- Saudi Arabia
	["flag_sn"] = {unicode = "1F1F8-1F1F3"},						-- Senegal
	["flag_rs"] = {unicode = "1F1F7-1F1F8"},						-- Serbia
	["flag_sc"] = {unicode = "1F1F8-1F1E8"},						-- Seychelles
	["flag_sl"] = {unicode = "1F1F8-1F1F1"},						-- Sierra Leone
	["flag_sg"] = {unicode = "1F1F8-1F1EC"},						-- Singapore
	["flag_sx"] = {unicode = "1F1F8-1F1FD"},						-- Sint Maarten
	["flag_sk"] = {unicode = "1F1F8-1F1F0"},						-- Slovakia
	["flag_si"] = {unicode = "1F1F8-1F1EE"},						-- Slovenia
	["flag_sb"] = {unicode = "1F1F8-1F1E7"},						-- Solomon Islands
	["flag_so"] = {unicode = "1F1F8-1F1F4"},						-- Somalia
	["flag_za"] = {unicode = "1F1FF-1F1E6"},						-- South Africa
	["flag_gs"] = {unicode = "1F1EC-1F1F8"},						-- South Georgia South Sandwich Islands
	["flag_kr"] = {unicode = "1F1F0-1F1F7"},						-- Korea
	["flag_ss"] = {unicode = "1F1F8-1F1F8"},						-- South Sudan
	["flag_es"] = {unicode = "1F1EA-1F1F8"},						-- Spain
	["flag_lk"] = {unicode = "1F1F1-1F1F0"},						-- Sri Lanka
	["flag_sd"] = {unicode = "1F1F8-1F1E9"},						-- Sudan
	["flag_sr"] = {unicode = "1F1F8-1F1F7"},						-- Suriname
	["flag_sz"] = {unicode = "1F1F8-1F1FF"},						-- Swaziland
	["flag_se"] = {unicode = "1F1F8-1F1EA"},						-- Sweden
	["flag_ch"] = {unicode = "1F1E8-1F1ED"},						-- Switzerland
	["flag_sy"] = {unicode = "1F1F8-1F1FE"},						-- Syria
	["flag_tw"] = {unicode = "1F1F9-1F1FC"},						-- Taiwan
	["flag_tj"] = {unicode = "1F1F9-1F1EF"},						-- Tajikistan
	["flag_tz"] = {unicode = "1F1F9-1F1FF"},						-- Tanzania
	["flag_th"] = {unicode = "1F1F9-1F1ED"},						-- Thailand
	["flag_tl"] = {unicode = "1F1F9-1F1F1"},						-- Timor Leste
	["flag_tg"] = {unicode = "1F1F9-1F1EC"},						-- Togo
	["flag_tk"] = {unicode = "1F1F9-1F1F0"},						-- Tokelau
	["flag_to"] = {unicode = "1F1F9-1F1F4"},						-- Tonga
	["flag_tt"] = {unicode = "1F1F9-1F1F9"},						-- Trinidad and Tobago
	["flag_tn"] = {unicode = "1F1F9-1F1F3"},						-- Tunisia
	["flag_tr"] = {unicode = "1F1F9-1F1F7"},						-- Turkey
	["flag_tm"] = {unicode = "1F1F9-1F1F2"},						-- Turkmenistan
	["flag_tc"] = {unicode = "1F1F9-1F1E8"},						-- Turks and Caicos Islands
	["flag_tv"] = {unicode = "1F1F9-1F1FB"},						-- Tuvalu
	["flag_ug"] = {unicode = "1F1FA-1F1EC"},						-- Uganda
	["flag_ua"] = {unicode = "1F1FA-1F1E6"},						-- Ukraine
	["flag_ae"] = {unicode = "1F1E6-1F1EA"},						-- United Arab Emirates
	["flag_uk"] = {unicode = "1F1EC-1F1E7"},						-- United Kingdom
	--["england"] = {unicode = "1F3F4-E0067-E0062-E0065-E006E-E0067-E007F"},						-- England (not supported)
	--["scotland"] = {unicode = "1F3F4-E0067-E0062-E0073-E0063-E0074-E007F"},						-- Scotland (not supported)
	--["wales"] = {unicode = "1F3F4-E0067-E0062-E0077-E006C-E0073-E007F"},						-- Wales (not supported)
	["flag_us"] = {unicode = "1F1FA-1F1F8"},						-- United States
	["flag_vi"] = {unicode = "1F1FB-1F1EE"},						-- US Virgin Islands
	["flag_uy"] = {unicode = "1F1FA-1F1FE"},						-- Uruguay
	["flag_uz"] = {unicode = "1F1FA-1F1FF"},						-- Uzbekistan
	["flag_vu"] = {unicode = "1F1FB-1F1FA"},						-- Vanuatu
	["flag_va"] = {unicode = "1F1FB-1F1E6"},						-- Vatican City
	["flag_ve"] = {unicode = "1F1FB-1F1EA"},						-- Venezuela
	["flag_vn"] = {unicode = "1F1FB-1F1F3"},						-- Vietnam
	["flag_wf"] = {unicode = "1F1FC-1F1EB"},						-- Wallis and Futuna
	["flag_eh"] = {unicode = "1F1EA-1F1ED"},						-- Western Sahara
	["flag_ye"] = {unicode = "1F1FE-1F1EA"},						-- Yemen
	["flag_zm"] = {unicode = "1F1FF-1F1F2"},						-- Zambia
	["flag_zw"] = {unicode = "1F1FF-1F1FC"},						-- Zimbabwe
	["flag_un"] = {unicode = "1F1FA-1F1F3"},						-- United Nations
}

ZO_ShallowTableCopy(customShortcodes, ee.emojiSCs)