if FCOGL == nil then FCOGL = {} end

ZO_CreateStringId("SI_BINDING_NAME_FCOGL_TOGGLEUI", GetString(SI_BINDING_NAME_FCOGL_TOGGLE))
ZO_CreateStringId("SI_BINDING_NAME_FCOGL_ROLL_THE_DICE", GetString(SI_BINDING_NAME_FCOGL_ROLL_THE_DICE))
ZO_CreateStringId("SI_BINDING_NAME_FCOGL_ROLL_THE_DICE_FOR_GUILD_SALES", GetString(SI_BINDING_NAME_FCOGL_ROLL_THE_DICE_FOR_GUILD_SALES))
ZO_CreateStringId("SI_BINDING_NAME_FCOGL_RESET_GUILD_SALES", GetString(SI_BINDING_NAME_FCOGL_RESET_GUILD_SALES))
ZO_CreateStringId("SI_BINDING_NAME_FCOGL_STOP_GUILD_SALES", GetString(SI_BINDING_NAME_FCOGL_STOP_GUILD_SALES))


