local SF = LibSFUtils

Slasher = {
	name = "Slasher",
	author = "Shadowfen",
	version = "2.48",
	savedVarVersion = "1",
}
local SL=Slasher
SL.displayName = SF.GetIconized(SL.name, SF.colors.gold.hex)
SL.author = SF.GetIconized(SL.author, SF.colors.purple.hex)
SL.evtmgr = SF.EvtMgr:New("Slasher")

SF.LoadLanguage(Slasher_localization_strings, "en")

-- Must be defined AFTER the LoadLanguage as we rely on the strings defined there for item[2]
SL.assts = {
	FENCE = {300,  SLASHER_SERVICE_FENCE, 'SI_BINDING_NAME_SLASHER_FENCE_TOGGLE'},
	PIR_FENCE = {300,  SLASHER_SERVICE_PIR_FENCE, 'SI_BINDING_NAME_SLASHER_PIRFENCE_TOGGLE'},
	CAM_FENCE = {14204,  SLASHER_SERVICE_CAM_FENCE, 'SI_BINDING_NAME_SLASHER_CAMFENCE_TOGGLE'},

	-- Bankers
	BANKER = {267, SLASHER_SERVICE_BANKER, 'SI_BINDING_NAME_SLASHER_BANKER_TOGGLE'},
	ALFIQ_BANKER = {6376, SLASHER_SERVICE_BANKER, 'SI_BINDING_NAME_SLASHER_ALFIQBANKER_TOGGLE'},
	CROW_BANKER = {8994, SLASHER_SERVICE_BANKER, 'SI_BINDING_NAME_SLASHER_CROWBANKER_TOGGLE'},
	CLOCK_BANKER = {9743, SLASHER_SERVICE_BANKER, 'SI_BINDING_NAME_SLASHER_CLOCKBANKER_TOGGLE'},
	MONST_BANKER = {11097, SLASHER_SERVICE_BANKER,'SI_BINDING_NAME_SLASHER_MONSTBANKER_TOGGLE'},  -- Pyroclast
	ERI_BANKER = {12413, SLASHER_SERVICE_BANKER, 'SI_BINDING_NAME_SLASHER_ERIBANKER_TOGGLE'},		-- Eri
	CEL_BANKER =  {13517, SLASHER_SERVICE_BANKER, 'SI_BINDING_NAME_SLASHER_CELBANKER_TOGGLE'},	-- Celia Tyde, Lost Fleet Bursar

	-- Merchants
	MERCHANT = {301, SLASHER_SERVICE_MERCHANT, 'SI_BINDING_NAME_SLASHER_MERCHANT_TOGGLE'},
	ALFIQ_MERCHANT = {6378, SLASHER_SERVICE_MERCHANT, 'SI_BINDING_NAME_SLASHER_ALFIQ_MERCHANT_TOGGLE'},
	CROW_MERCHANT = {8995, SLASHER_SERVICE_MERCHANT, 'SI_BINDING_NAME_SLASHER_CROW_MERCHANT_TOGGLE'},
	CLOCK_MERCHANT = {9744, SLASHER_SERVICE_MERCHANT, 'SI_BINDING_NAME_SLASHER_CLOCK_MERCHANT_TOGGLE'},
	MONST_MERCHANT = {11059, SLASHER_SERVICE_MERCHANT, 'SI_BINDING_NAME_SLASHER_MONST_MERCHANT_TOGGLE'},	-- Hoarfrost
	XYN_MERCHANT = {12414, SLASHER_SERVICE_MERCHANT, 'SI_BINDING_NAME_SLASHER_XYN_MERCHANT_TOGGLE'},	-- Xyn
	TERI_MERCHANT = {13066, SLASHER_SERVICE_MERCHANT, 'SI_BINDING_NAME_SLASHER_TERI_MERCHANT_TOGGLE'},	-- Terilorne

	-- deconstructors
	DECON = {10184, SLASHER_SERVICE_GIL_DECON, 'SI_BINDING_NAME_SLASHER_DECON_TOGGLE'},		-- Giladil
	FARG_DECON = {10617, SLASHER_SERVICE_FARG_DECON, 'SI_BINDING_NAME_SLASHER_FARG_DECON_TOGGLE'},	-- Aderene
	TZOZ_DECON = {11877, SLASHER_SERVICE_TZOZ_DECON, 'SI_BINDING_NAME_SLASHER_TZOZ_DECON_TOGGLE'}, -- Tzozabrar
	SIL_DECON = {13063, SLASHER_SERVICE_SIL_DECON, 'SI_BINDING_NAME_SLASHER_SIL_DECON_TOGGLE'}, -- Siluruz
	POR_DECON = {14018, SLASHER_SERVICE_POR_DECON, 'SI_BINDING_NAME_SLASHER_POR_DECON_TOGGLE'}, -- Portius

	-- Companions
	BASTIAN = {9245, SLASHER_SERVICE_BASTIAN, 'SI_BINDING_NAME_SLASHER_BASTIAN_TOGGLE'},		-- 9440 is houseguest
	MIRRI = {9353, SLASHER_SERVICE_MIRRI, 'SI_BINDING_NAME_SLASHER_MIRRI_TOGGLE'},		-- 9441 is houseguest
	ISOBEL = {9912, SLASHER_SERVICE_ISOBEL, 'SI_BINDING_NAME_SLASHER_ISOBEL_TOGGLE'},
	EMBER = {9911, SLASHER_SERVICE_EMBER, 'SI_BINDING_NAME_SLASHER_EMBER_TOGGLE'},
	SHARP = {11113, SLASHER_SERVICE_SHARP, 'SI_BINDING_NAME_SLASHER_SHARP_TOGGLE'},
	AZANDAR = {11114, SLASHER_SERVICE_AZANDAR, 'SI_BINDING_NAME_SLASHER_AZANDAR_TOGGLE'},
	TANLORIN = {12172, SLASHER_SERVICE_TANLORIN, 'SI_BINDING_NAME_SLASHER_TANLORIN_TOGGLE'},
	ZERITH = {12173, SLASHER_SERVICE_ZERITH, 'SI_BINDING_NAME_SLASHER_ZERITH_TOGGLE'},

	--Armorers
	ARMORER = {9745, SLASHER_SERVICE_ARMORER, 'SI_BINDING_NAME_SLASHER_ARMORER_TOGGLE'},
	GHRASHROG = {9745, SLASHER_SERVICE_ARMORER, 'SI_BINDING_NAME_SLASHER_ARMORER_TOGGLE'},
	ZUQOTH = {10618, SLASHER_SERVICE_ZUQOTH, 'SI_BINDING_NAME_SLASHER_ZUQOTH_TOGGLE'},
	DRINWETH = {11876, SLASHER_SERVICE_DRINWETH, 'SI_BINDING_NAME_SLASHER_DRINWETH_TOGGLE'},
	VOKO = {13518, SLASHER_SERVICE_VOKO, 'SI_BINDING_NAME_SLASHER_VOKO_TOGGLE'},
}

SL.companions = {
	SL.assts[BASTIAN],		-- 9440 is houseguest
	SL.assts[MIRRI],
	SL.assts[ISOBEL],
	SL.assts[EMBER],
	SL.assts[SHARP],
	SL.assts[AZANDAR],
	SL.assts[TANLORIN],
	SL.assts[ZERITH],
}

SL.holiday_items = {
	JUBALEE_CAKE = 356,
	JUBALEE_CAKE2 = 1109,
	JUBALEE_CAKE3 = 4786,
	JUBALEE_CAKE2019 = 5886,
	JUBALEE_CAKE2020 = 7619,
	JUBALEE_CAKE2021 = 9012,
	JUBALEE_CAKE2022 = 10287,
	JUBALEE_CAKE2023 = 11089,
	JUBALEE_CAKE2024 = 12422,
	JUBALEE_CAKE2025 = 13520,
	JUBALEE_CAKE2026 = 14325,
	WITCHMOTHERS_WHISTLE = 479,
	SWORD_SWALLOWERS_BLADE = 597,
	JUGGLERS_KNIVES = 598,
	FIRE_BREATHERS_TORCHES = 600,
	MUDBALL_POUCH = 601,
	PIE_OF_MISRULE = 1167,
	BREDAS_MEAD_CUP = 1168,
}

SL.other = {
	ANTIQUARIAN_EYE = 8006,
}
