-- Name: SmartBags
-- Version: 1.3.5a
-- Author: Reikan
-- Localization functions (FR / DE / EN)
-- !If translations can be improved, please do not hesitate to let me know!

-- Localisation variables
SB_Lang = "EN"
SB_Lang_Mode_Bag = ""
SB_Lang_Mode_Bank = ""
SB_Lang_Language = ""

-- LootGoldLog
SB_Lang_Received = ""
SB_Lang_PartyReceived = ""
SB_Lang_Lost = ""
SB_Lang_Gold = ""
SB_Lang_Golds = ""

-- Keybind text
SB_Lang_Keybind_Text = ""

-- Settings panel
SB_Lang_Settings_MainOptionsTitle = ""
SB_Lang_Settings_LockUnlockFrame = ""
SB_Lang_Settings_LockUnlockFrame_ToolTip = ""
SB_Lang_Settings_ShowHideInDialog = ""
SB_Lang_Settings_ShowHideInDialog_ToolTip = ""
SB_Lang_Settings_SwitchBankBagAuto = ""
SB_Lang_Settings_SwitchBankBagAuto_ToolTip = ""
SB_Lang_Settings_NormalStateColor = ""
SB_Lang_Settings_NormalStateColor_ToolTip = ""
SB_Lang_Settings_WarningStateColor = ""
SB_Lang_Settings_WarningStateColor_ToolTip = ""
SB_Lang_Settings_FullStateColor = ""
SB_Lang_Settings_FullStateColor_ToolTip = ""
SB_Lang_Settings_PercentWarningState = ""
SB_Lang_Settings_PercentWarningState_ToolTip = ""
SB_Lang_Settings_LangOptionsTitle = ""
SB_Lang_Settings_LangOptionsSelection = ""
SB_Lang_Settings_LangOptionsSelection_ToolTip = ""
SB_Lang_Settings_LangOptionsSelection_Warning_ToolTip = ""
-- LootGoldLog settings
SB_Lang_Settings_LootGoldLog_Title = ""
SB_Lang_Settings_LootGoldLog_Enable = ""
SB_Lang_Settings_LootGoldLog_Enable_ToolTip = ""
SB_Lang_Settings_LootGoldLog_ReceiveLootColor = ""
SB_Lang_Settings_LootGoldLog_ReceiveGoldColor = ""
SB_Lang_Settings_LootGoldLog_LostColor = ""
SB_Lang_Settings_LootGoldLog_ShowGolds = ""
SB_Lang_Settings_LootGoldLog_ShowGolds_Tooltip = ""	
SB_Lang_Settings_LootGoldLog_ShowTotalItems = ""
SB_Lang_Settings_LootGoldLog_ShowTotalItems_Tooltip = ""
SB_Lang_Settings_LootGoldLog_ShowPartyItems = ""
SB_Lang_Settings_LootGoldLog_ShowPartyItems_Tooltip = ""
SB_Lang_Settings_LootGoldLog_PartyColor = ""

-- Language definition
function SmartBags.SetLangVariables()
	-- FR
	if (SmartBags.settings.LocalLang == "FR") then
		SB_Lang_Mode_Bag = "[Sac]"
		SB_Lang_Mode_Bank = "[Banque]"
		SB_Lang_Language = "Langue"
		-- Keybind text
		SB_Lang_Keybind_Text = "Changement de mode"
		-- LootGoldLog
		SB_Lang_Received = "Vous recevez "
		SB_Lang_PartyReceived = " re\195\167oit "
		SB_Lang_Gold = "pi\195\168ce d'or"
		SB_Lang_Golds = "pi\195\168ces d'or"
		SB_Lang_Lost = "Vous perdez "
		-- Settings panel
		SB_Lang_Settings_MainOptionsTitle = "Options principales"
		SB_Lang_Settings_LockUnlockFrame = "Autoriser le d\195\169placement de la fen\195\170tre"
		SB_Lang_Settings_LockUnlockFrame_ToolTip = "Active ou d\195\169sactive le d\195\169placement de la fen\195\170tre"
		SB_Lang_Settings_SwitchBankBagAuto = "Switch auto \195\160 l'ouverture de la banque"
		SB_Lang_Settings_SwitchBankBagAuto_ToolTip = "Passe en mode 'sac' lors de l'ouverture de la banque automatiquement"
		SB_Lang_Settings_ShowHideInDialog = "Afficher SmartBags lors des dialogues"
		SB_Lang_Settings_ShowHideInDialog_ToolTip = "Activer ou desactiver cette option affichera ou cachera SmartBags lors des interactions avec les PNJ"
		SB_Lang_Settings_NormalStateColor = "Couleur de l'\195\169tat normal"
		SB_Lang_Settings_NormalStateColor_ToolTip = "Selectionner la couleur de l'\195\169tat normal (lorsque les sacs sont normalement remplis)"
		SB_Lang_Settings_WarningStateColor = "Couleur de l'\195\169tat d'alerte"
		SB_Lang_Settings_WarningStateColor_ToolTip = "Selectionner la couleur de l'\195\169tat d'alerte (lorsque les sacs sont presque pleins)"
		SB_Lang_Settings_FullStateColor = "Couleur de l'\195\169tat plein"
		SB_Lang_Settings_FullStateColor_ToolTip = "Selectionner la couleur de l'\195\169tat plein (lorsque les sacs sont pleins)"
		SB_Lang_Settings_PercentWarningState = "Pourcentage de l'\195\169tat d'alerte"
		SB_Lang_Settings_PercentWarningState_ToolTip = "Selectionner le pourcentage du declenchement de l'\195\169tat d'alerte"
		SB_Lang_Settings_LangOptionsTitle = "Options de localisation"
		SB_Lang_Settings_LangOptionsSelection = "Selectionner la langue"
		SB_Lang_Settings_LangOptionsSelection_ToolTip = "Langue d'affichage de l'addon"
		SB_Lang_Settings_LangOptionsSelection_Warning_ToolTip = "Modifier cette option rechargera l'interface"
		SB_Lang_Settings_LootGoldLog_Title = "Options de SmartBags LootGoldLog"
		SB_Lang_Settings_LootGoldLog_Enable = "Activer SmartBags LootGoldLog"
		SB_Lang_Settings_LootGoldLog_Enable_ToolTip = "Active / d\195\169sactive la fonction d'affichage des loots et de l'argent dans la fen\195\170tre de chat"
		SB_Lang_Settings_LootGoldLog_ReceiveLootColor = "Couleur du texte pour les loots"
		SB_Lang_Settings_LootGoldLog_ReceiveGoldColor = "Couleur du texte pour l'or"
		SB_Lang_Settings_LootGoldLog_LostColor = "Couleur d'affichage pour une perte"
		SB_Lang_Settings_LootGoldLog_ShowGolds = "Afficher les gains / pertes d'or"
		SB_Lang_Settings_LootGoldLog_ShowGolds_Tooltip = "Afficher les gains ou les pertes d'or dans le chat"	
		SB_Lang_Settings_LootGoldLog_ShowTotalItems = "Afficher le total d'objets"
		SB_Lang_Settings_LootGoldLog_ShowTotalItems_Tooltip = "Affiche le total d'objets lors du ramassage d'un objet (regarde dans l'inventaire et la banque)"
		SB_Lang_Settings_LootGoldLog_ShowPartyItems = "Afficher les loots de groupe"
		SB_Lang_Settings_LootGoldLog_ShowPartyItems_Tooltip = "Affiche les loots que recoivent les membres de votre groupe"
		SB_Lang_Settings_LootGoldLog_PartyColor = "Couleur du butin de groupe"
	-- DE
	elseif (SmartBags.settings.LocalLang == "DE") then
		SB_Lang_Mode_Bag = "[Tasche]"
		SB_Lang_Mode_Bank = "[Bank]"
		SB_Lang_Language = "Sprache"
		-- Keybind text
		SB_Lang_Keybind_Text = "Toggle-modus"
		-- LootGoldLog
		SB_Lang_Received = "Sie erhalten "
		SB_Lang_PartyReceived = " erhalt "
		SB_Lang_Gold = "goldmunze"
		SB_Lang_Golds = "goldmunzen"
		SB_Lang_Lost = "Sie verlieren "
		-- Settings panel
		SB_Lang_Settings_MainOptionsTitle = "Smartbags Hauptoptionen"
		SB_Lang_Settings_LockUnlockFrame = "Entsperren SmartBags rahmen bewegung"
		SB_Lang_Settings_LockUnlockFrame_ToolTip = "SmartBags umzug funktionen erm\195\182glichen"
		SB_Lang_Settings_SwitchBankBagAuto = "Auto kippschalter, wenn Bank ist offen"
		SB_Lang_Settings_SwitchBankBagAuto_ToolTip = "Wechseln beutel-modus, wenn Bank ist offen"
		SB_Lang_Settings_ShowHideInDialog = "Show SmartBags bei dialog"
		SB_Lang_Settings_ShowHideInDialog_ToolTip = "Show / hide SmartBags w\195\164hrend NPC dialog"
		SB_Lang_Settings_NormalStateColor = "Normalzustand farbe"
		SB_Lang_Settings_NormalStateColor_ToolTip = "W\195\164hlen sie den normalzustand farbe (bei taschen ist nicht in alarmzustand)"
		SB_Lang_Settings_WarningStateColor = "Warnzustand farbe"
		SB_Lang_Settings_WarningStateColor_ToolTip = "W\195\164hlen sie den warnzustand farbe (bei taschen ist fast voll)"
		SB_Lang_Settings_FullStateColor = "Volle staatliche farbe"
		SB_Lang_Settings_FullStateColor_ToolTip = "W\195\164hlen sie die volle staatliche farbe (bei taschen voll ist)"
		SB_Lang_Settings_PercentWarningState = "Prozent warnzustand"
		SB_Lang_Settings_PercentWarningState_ToolTip = "W\195\164hlen sie den prozentwert, wenn indikator \195\164nderung warnzustand"
		SB_Lang_Settings_LangOptionsTitle = "Sprachoptionen"
		SB_Lang_Settings_LangOptionsSelection = "W\195\164hlen sie die sprache"
		SB_Lang_Settings_LangOptionsSelection_ToolTip = "AddOn sprache"
		SB_Lang_Settings_LangOptionsSelection_Warning_ToolTip = "\195\132ndern sie diese option wird neu geladen werden ui"
		SB_Lang_Settings_LootGoldLog_Title = "SmartBags LootGoldLog optionen"
		SB_Lang_Settings_LootGoldLog_Enable = "Aktivieren SmartBags LootGoldLog"
		SB_Lang_Settings_LootGoldLog_Enable_ToolTip = "Aktivieren SmartBags LootGoldLog funktion im chat-protokoll ?"
		SB_Lang_Settings_LootGoldLog_ReceiveLootColor = "Textfarbe f\195\188r empfangene einzelteile"
		SB_Lang_Settings_LootGoldLog_ReceiveGoldColor = "Textfarbe f\195\188r empfangene gold"
		SB_Lang_Settings_LootGoldLog_LostColor = "Textfarbe f\195\188r verlorene gold (en)"
		SB_Lang_Settings_LootGoldLog_ShowGolds = "Erhalten / verlorene gold show"
		SB_Lang_Settings_LootGoldLog_ShowGolds_Tooltip = "Erhalten oder im chat-lrotokoll verloren show gold"
		SB_Lang_Settings_LootGoldLog_ShowTotalItems = "Gesamtanzahl der objekte bei abholung zeigen"
		SB_Lang_Settings_LootGoldLog_ShowTotalItems_Tooltip = "Zeigen insgesamt positionen bei der kommissionierung (suche im inventar und der bank und zeigt es)"
		SB_Lang_Settings_LootGoldLog_ShowPartyItems = "Show-gruppe gepl\195\188ndert artikel"
		SB_Lang_Settings_LootGoldLog_ShowPartyItems_Tooltip = "Show erhielt artikel ihrer gruppe"
		SB_Lang_Settings_LootGoldLog_PartyColor = "Textfarbe f\195\188r gepl\195\188ndert gruppenelement"
	-- EN
	elseif (SmartBags.settings.LocalLang == "EN") then
		SB_Lang_Mode_Bag = "[Bag]"
		SB_Lang_Mode_Bank = "[Bank]"
		SB_Lang_Language = "Language"
		-- Keybind text
		SB_Lang_Keybind_Text = "Toggle mode"
		-- LootGoldLog
		SB_Lang_Received = "You receive "
		SB_Lang_PartyReceived = " received "
		SB_Lang_Gold = "gold"
		SB_Lang_Golds = "golds"	
		SB_Lang_Lost = "You lose "
		-- Settings panel
		SB_Lang_Settings_MainOptionsTitle = "SmartBags main options"
		SB_Lang_Settings_LockUnlockFrame = "Unlock SmartBags frame movement"
		SB_Lang_Settings_LockUnlockFrame_ToolTip = "Enable SmartBags move functions"
		SB_Lang_Settings_SwitchBankBagAuto = "Auto toggle when bank is open"
		SB_Lang_Settings_SwitchBankBagAuto_ToolTip = "Toggle bag mode when bank is open"
		SB_Lang_Settings_ShowHideInDialog = "Show SmartBags during dialog"
		SB_Lang_Settings_ShowHideInDialog_ToolTip = "Show / hide SmartBags during NPC dialogs"
		SB_Lang_Settings_NormalStateColor = "Normal state color"
		SB_Lang_Settings_NormalStateColor_ToolTip = "Select the normal state color (when bags is not in warning state)"
		SB_Lang_Settings_WarningStateColor = "Warning state color"
		SB_Lang_Settings_WarningStateColor_ToolTip = "Select the warning state color (when bags is almost full)"
		SB_Lang_Settings_FullStateColor = "Full state color"
		SB_Lang_Settings_FullStateColor_ToolTip = "Select the full state color (when bags is full)"
		SB_Lang_Settings_PercentWarningState = "Percent warning state"
		SB_Lang_Settings_PercentWarningState_ToolTip = "Select the percent value when indicator change to warning state"
		SB_Lang_Settings_LangOptionsTitle = "Language options"
		SB_Lang_Settings_LangOptionsSelection = "Select language"
		SB_Lang_Settings_LangOptionsSelection_ToolTip = "AddOn language"
		SB_Lang_Settings_LangOptionsSelection_Warning_ToolTip = "Change this option will be reload ui"
		SB_Lang_Settings_LootGoldLog_Title = "SmartBags LootGoldLog options"
		SB_Lang_Settings_LootGoldLog_Enable = "Enable SmartBags LootGoldLog"
		SB_Lang_Settings_LootGoldLog_Enable_ToolTip = "Enable SmartBags LootGoldLog function in chat log ?"
		SB_Lang_Settings_LootGoldLog_ReceiveLootColor = "Text color for received items"
		SB_Lang_Settings_LootGoldLog_ReceiveGoldColor = "Text color for received gold"
		SB_Lang_Settings_LootGoldLog_LostColor = "Text color for lost gold(s)"
		SB_Lang_Settings_LootGoldLog_ShowGolds = "Show received / lost gold"
		SB_Lang_Settings_LootGoldLog_ShowGolds_Tooltip = "Show golds received or lost in the chat log"
		SB_Lang_Settings_LootGoldLog_ShowTotalItems = "Show total items on pickup"
		SB_Lang_Settings_LootGoldLog_ShowTotalItems_Tooltip = "Show total items when picking (search in the inventory and the bank and display it)"
		SB_Lang_Settings_LootGoldLog_ShowPartyItems = "Show group looted items"
		SB_Lang_Settings_LootGoldLog_ShowPartyItems_Tooltip = "Show received items of your group"
		SB_Lang_Settings_LootGoldLog_PartyColor = "Text color for looted group item"
	end
end