ZO_CreateStringId("SI_BINDING_NAME_EBPIXARTLIVESTATS_TOGGLE_WINDOW", "Afficher / masquer EB-Pixart Live Stats")
ZO_CreateStringId("SI_BINDING_NAME_EBPIXARTLIVESTATS_TOGGLE_MAIN_WINDOW", "Afficher / masquer la fenêtre principale")
ZO_CreateStringId("SI_BINDING_NAME_EBPIXARTLIVESTATS_TOGGLE_HEAL_WINDOW", "Afficher / masquer la fenêtre d'analyse des soins")
ZO_CreateStringId("SI_BINDING_NAME_EBPIXARTLIVESTATS_SHARE_CURRENT_SESSION", "Partager la dernière session")
ZO_CreateStringId("SI_BINDING_NAME_EBPIXARTLIVESTATS_SHARE_CURRENT_HEALS", "Partager les soins de la dernière session")
ZO_CreateStringId("SI_BINDING_NAME_EBPIXARTLIVESTATS_MANUAL_RESET_SESSION", "Réinitialiser la session actuelle")

ZO_CreateStringId("EBPXLIVESTATS_CHAT_LOADED", "<<1>> v<<2>> chargé.")
ZO_CreateStringId("EBPXLIVESTATS_CHAT_NOT_READY", "L'interface n'est pas encore prête.")
ZO_CreateStringId("EBPXLIVESTATS_CHAT_LAM_MISSING", "LibAddonMenu2.0 est introuvable. Les options ne seront pas disponibles.")

ZO_CreateStringId("EBPXLIVESTATS_UI_LOADING", "Chargement des statistiques...")
ZO_CreateStringId("EBPXLIVESTATS_UI_TITLE", "<<1>>")
ZO_CreateStringId("EBPXLIVESTATS_UI_EMPTY", "Aucune statistique affichée\nActivez des lignes dans les réglages de l'addon")
ZO_CreateStringId("EBPXLIVESTATS_UI_SECTION_COMBAT", "Combat")
ZO_CreateStringId("EBPXLIVESTATS_UI_SECTION_PVE", "Stats PVE")
ZO_CreateStringId("EBPXLIVESTATS_UI_SECTION_PVP", "Stats PVP")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_DPS", "DPS")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_DAMAGE", "Dégâts")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_HEALING", "Soins")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_COMBAT", "État de combat")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_SPELL_CRIT", "Critiques magiques")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_WEAPON_CRIT", "Critiques physiques")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_SPELL_POWER", "Dégâts magiques")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_WEAPON_POWER", "Dégâts physiques")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_SPELL_PEN", "Pénétration magique")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_WEAPON_PEN", "Pénétration physique")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_OUTGOING_HEALING_PERCENT", "Soins (en %)")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_INCOMING_HEALING_PERCENT", "Soins reçus (en %)")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_BLOCK_PERCENT", "Pourcentage de blocage (en %)")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_BLOCK_COST", "Coût de blocage")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_MOVE_SPEED_PERCENT", "Vitesse de déplacement (en %)")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_PHYSICAL_RESISTANCE", "Résistances physiques")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_SPELL_RESISTANCE", "Résistances magiques")
ZO_CreateStringId("EBPXLIVESTATS_LABEL_CRITICAL_RESISTANCE", "Résistance aux coups critiques")

ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_DESCRIPTION", "Configuration de l'addon EB-Pixart Live Stats.")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_WINDOW_HEADER", "Fenêtre principale")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_UNLOCK_NAME", "Déverrouiller la fenêtre")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_UNLOCK_TOOLTIP", "Autorise le déplacement de la fenêtre de statistiques.")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HIDE_NAME", "Masquer la fenêtre")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HIDE_TOOLTIP", "Affiche ou masque la fenêtre de statistiques.")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_RESET_POSITION_NAME", "Réinitialiser la position")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_RESET_POSITION_TOOLTIP", "Replace la fenêtre à sa position par défaut.")

ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_MAIN_STATS_HEADER", "Statistiques affichées - Fenêtre principale")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_COMBAT_SUBHEADER", "Combat")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_PVE_SUBHEADER", "Stats PVE")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_PVP_SUBHEADER", "Stats PVP")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_DPS_NAME", "Afficher le DPS")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_DAMAGE_NAME", "Afficher les dégâts")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_HEALING_NAME", "Afficher les soins")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_COMBAT_STATE_NAME", "Afficher l'état de combat")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_SPELL_CRIT_NAME", "Afficher les critiques magiques")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_WEAPON_CRIT_NAME", "Afficher les critiques physiques")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_SPELL_POWER_NAME", "Afficher les dégâts magiques")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_WEAPON_POWER_NAME", "Afficher les dégâts physiques")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_SPELL_PEN_NAME", "Afficher la pénétration magique")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_WEAPON_PEN_NAME", "Afficher la pénétration physique")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_OUTGOING_HEALING_PERCENT_NAME", "Afficher les soins (en %)")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_INCOMING_HEALING_PERCENT_NAME", "Afficher les soins reçus (en %)")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_BLOCK_PERCENT_NAME", "Afficher le pourcentage de blocage (en %)")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_BLOCK_COST_NAME", "Afficher le coût de blocage")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_MOVE_SPEED_PERCENT_NAME", "Afficher la vitesse de déplacement (en %)")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_PHYSICAL_RESISTANCE_NAME", "Afficher les résistances physiques")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_SPELL_RESISTANCE_NAME", "Afficher les résistances magiques")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHOW_CRITICAL_RESISTANCE_NAME", "Afficher la résistance aux coups critiques")

ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_MAIN_APPEARANCE_HEADER", "Apparence - Fenêtre principale")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_LABEL_FONT_SIZE_NAME", "Taille du texte - libellés")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_VALUE_FONT_SIZE_NAME", "Taille du texte - valeurs")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_WINDOW_WIDTH_NAME", "Largeur de la fenêtre")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_WINDOW_HEIGHT_NAME", "Hauteur de la fenêtre")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_TITLE_COLOR_NAME", "Couleur du titre")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_LABEL_COLOR_NAME", "Couleur des libellés")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_VALUE_COLOR_NAME", "Couleur des valeurs")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_RESET_APPEARANCE_NAME", "Réinitialiser l'apparence")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_RESET_APPEARANCE_TOOLTIP", "Remet uniquement les réglages visuels par défaut.")

ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_HEADER", "Fenêtre analyse des soins")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_SHOW_NAME", "Afficher la fenêtre d'analyse des soins")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_UNLOCK_NAME", "Déverrouiller la fenêtre d'analyse des soins")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_RESET_POSITION_NAME", "Réinitialiser la position")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_AUTO_TRACKING_NAME", "Suivi automatique des soins")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_AUTO_TRACKING_TOOLTIP", "Active automatiquement le suivi des soins. Désactivé par défaut pour des tests manuels propres.")

ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_APPEARANCE_HEADER", "Apparence - Fenêtre analyse des soins")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_LABEL_FONT_SIZE_NAME", "Taille du texte - libellés")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_VALUE_FONT_SIZE_NAME", "Taille du texte - valeurs")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_WIDTH_NAME", "Largeur de la fenêtre")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_HEIGHT_NAME", "Hauteur de la fenêtre")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_TITLE_COLOR_NAME", "Couleur du titre")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_LABEL_COLOR_NAME", "Couleur des libellés")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_VALUE_COLOR_NAME", "Couleur des valeurs")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_RESET_APPEARANCE_NAME", "Réinitialiser l'apparence")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_HEAL_WINDOW_RESET_APPEARANCE_TOOLTIP", "Remet uniquement les réglages visuels de la fenêtre d'analyse des soins par défaut.")

ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SESSION_HEADER", "Session automatique")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_AUTO_RESET_ENABLED_NAME", "Activer la réinitialisation automatique")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_AUTO_RESET_ENABLED_TOOLTIP", "Bascule la session actuelle en dernière session si elle contient des données, puis réinitialise les compteurs.")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_AUTO_RESET_DELAY_NAME", "Délai avant réinitialisation (secondes)")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_AUTO_RESET_DELAY_TOOLTIP", "Délai d'inactivité avant la réinitialisation automatique.")

ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SESSION_SHARE_HEADER", "Partage et réinitialisation")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_MANUAL_RESET_NAME", "Réinitialiser la session actuelle")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_MANUAL_RESET_TOOLTIP", "Bascule la session actuelle en dernière session si elle contient des données, puis réinitialise les compteurs.")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHARE_CURRENT_NAME", "Partager la session actuelle")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHARE_LAST_NAME", "Partager la dernière session")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHARE_CURRENT_HEALS_NAME", "Partager les soins de la session actuelle")
ZO_CreateStringId("EBPXLIVESTATS_SETTINGS_SHARE_LAST_HEALS_NAME", "Partager les soins de la dernière session")
