---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by elwoo.
--- DateTime: 2021-07-03 17:52
---


local DEFAULT_TEXT = "n/a"
local TIME_PLAYED_PATTERN = "<<1>> |c<<3>>(<<2>>)|r"
local SV_VERSION = 1

local TIME = "TIME"
local TIME_PLAYED = "TIME_PLAYED"

local ORDER = {
    [1] = TIME,
    [2] = TIME_PLAYED,
}

local ICONS = {
    [TIME] = "/esoui/art/hud/gamepad/gp_radialicon_defer_down.dds",
    [TIME_PLAYED] = "/esoui/art/tutorial/gamepad/gp_notificationicon_campaignqueue.dds",
}

local NAMES = {
    [TIME] = GetString(SI_TRADINGHOUSELISTINGSORTTYPE0),
    [TIME_PLAYED] = GetString(SI_GUILD_FINDER_GUILD_INFO_PLAYTIME_HEADER),
}

------------------------------
-- Class definition
 YeOldeTime = YeOldeInfoBar_Base:Subclass()

function  YeOldeTime:InitializeControls()
    self.blocs = {}
    for _, type in ipairs(ORDER) do
        self.blocs[type] = self.uiBar:AddContentBloc(type, ICONS[type], DEFAULT_TEXT)
        if not self.SV.Show[type] then
            self.uiBar:SetBlocHidden(self.blocs[type], true)
        end
    end

    self.onUpdateFn = function() self:OnTimeUpdate() end
end

local function FormatTime(seconds)
    local result
    if seconds < ZO_ONE_HOUR_IN_SECONDS then
        result = zo_strformat(SI_TIME_FORMAT_MINUTES, math.floor(seconds / ZO_ONE_MINUTE_IN_SECONDS))
    elseif seconds < ZO_ONE_DAY_IN_SECONDS then
        local hours = math.floor(seconds / ZO_ONE_HOUR_IN_SECONDS)
        local minutes = math.floor((seconds % ZO_ONE_HOUR_IN_SECONDS) / ZO_ONE_MINUTE_IN_SECONDS)
        result = zo_strformat(SI_TIME_FORMAT_HHMM_DESC_SHORT, hours, minutes)
    else
        result = zo_strformat(SI_TIME_FORMAT_HOURS, math.floor(seconds / ZO_ONE_HOUR_IN_SECONDS))
    end
    return result
end

function YeOldeTime:UpdateIcons()
    for _, type in ipairs(ORDER) do
        if self.blocs[type] ~= nil then
            self.blocs[type]:ShowIcon(self.SV.ShowIcons)
        end
    end
end

function YeOldeTime:SetTimeFormat()
    if self.SV.TwentyFourHourFormat then
        ZO_SetClockFormat(TIME_FORMAT_PRECISION_TWENTY_FOUR_HOUR)
    else
        ZO_SetClockFormat(TIME_FORMAT_PRECISION_TWELVE_HOUR_NO_SECONDS)
    end
end

function YeOldeTime:OnTimeUpdate()
    local text, secondsUntilNextUpdate = ZO_FormatClockTime()
    local timePlayed = FormatTime(GetGameTimeMilliseconds() / ZO_ONE_SECOND_IN_MILLISECONDS)
    local totalTimePlayed = FormatTime(GetSecondsPlayed())

    if self.SV.Show[TIME] then
        self.blocs[TIME]:SetText(text)
    end
    if self.SV.Show[TIME_PLAYED] then
        self.blocs[TIME_PLAYED]:SetText(zo_strformat(TIME_PLAYED_PATTERN, timePlayed, totalTimePlayed, YeOldeInfos.Colors.GRAY:ToHex()))
    end


    if self.nextUpdateIn ~= secondsUntilNextUpdate then
        self.nextUpdateIn = secondsUntilNextUpdate
        EVENT_MANAGER:UnregisterForUpdate(self.eventNamespace)
        EVENT_MANAGER:RegisterForUpdate(self.eventNamespace, self.nextUpdateIn*ZO_ONE_SECOND_IN_MILLISECONDS, self.onUpdateFn)
    end
end


function  YeOldeTime:OnActivate(value)
    if value then
        self:SetTimeFormat()
        self:OnTimeUpdate()
        self:UpdateIcons()
    else
        EVENT_MANAGER:UnregisterForUpdate(self.eventNamespace)
    end
end


function YeOldeTime:InitializeSavedVars()
    -- If Version = 0, we need to initialize vars
    if self.SV.Version == 0 then
        self.SV.Show = {
            [TIME] = true,
            [TIME_PLAYED] = true,
        }
        self.SV.TwentyFourHourFormat = true
        self.SV.ShowIcons = true
    else
        if self.SV.TwentyFourHourFormat == nil then self.SV.TwentyFourHourFormat = true end
        if self.SV.ShowIcons == nil then self.SV.ShowIcons = true end
    end
    self.SV.Version = SV_VERSION
end

function  YeOldeTime:InitializeSettingsMenu(controls)
    controls[#controls + 1] = {
        type = "checkbox",
        name = YeOldeInfos.lang[SI_YEOLDEINFOS_TIME_FORMAT],
        tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_TIME_FORMAT],
        getFunc = function() return self.SV.TwentyFourHourFormat end,
        setFunc = function(value)
            self.SV.TwentyFourHourFormat = value
            self:SetTimeFormat()
            self:OnTimeUpdate()
        end,
    }
    controls[#controls + 1] = {
        type = "checkbox",
        name = YeOldeInfos.lang[SI_YEOLDEINFOS_TIME_SHOW_ICONS],
        tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_TIME_SHOW_ICONS],
        getFunc = function() return self.SV.ShowIcons end,
        setFunc = function(value)
            self.SV.ShowIcons = value
            self:UpdateIcons()
        end,
    }
    controls[#controls + 1] = {
        type = "divider",
        reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls)
    }
    controls[#controls + 1] = {
        type = "description",
        title = zo_strformat(YeOldeInfos.SETTING_DESC_TITLE_PATTERN, YeOldeInfos.lang[SI_YEOLDEINFOS_BAR_CONTENT]),
        reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls)
    }
    for _, type in ipairs(ORDER) do
        controls[#controls + 1] = {
            type = "checkbox",
            name = NAMES[type],
            getFunc = function() return self.SV.Show[type] end,
            setFunc = function(value)
                self.SV.Show[type] = value
                self.uiBar:SetBlocHidden(self.blocs[type], not value)
                if value then
                    self:SetTimeFormat()
                    self:OnTimeUpdate()
                    self:UpdateIcons()
                end
            end,
        }
    end


    local options = {
        type = 'submenu',
        name = GetString(SI_TRADINGHOUSELISTINGSORTTYPE0),
        controls = controls,
    }
    return options
end
