---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2021-03-15 11:48
---
---
---TODO:
--- Add option to hide bar if quests are completed for today.

YeOldeCrafting = YeOldeInfoBar_Base:Subclass()

local ICON_SIZE = 28
local SV_VERSION = 2

local STATUS = YeOldeInfos.CraftingQuestStatus
local STATUS_COLORS = {
	[STATUS.UNAVAILABLE] = YeOldeInfos.Colors.DISABLED,
	[STATUS.AVAILABLE] = YeOldeInfos.Colors.WHITE,
	[STATUS.ACTIVE] = YeOldeInfos.Colors.GOLD,
	[STATUS.READY_TO_DELIVER] = YeOldeInfos.Colors.GREEN,
	[STATUS.COMPLETED] = YeOldeInfos.Colors.DISABLED,
	[STATUS.UNKNOWN] = YeOldeInfos.Colors.DISABLED,
}

local CRAFTING_ORDER = {
	CRAFTING_TYPE_CLOTHIER,
	CRAFTING_TYPE_BLACKSMITHING,
	CRAFTING_TYPE_WOODWORKING,
	CRAFTING_TYPE_PROVISIONING,
	CRAFTING_TYPE_ENCHANTING,
	CRAFTING_TYPE_JEWELRYCRAFTING,
	CRAFTING_TYPE_ALCHEMY,
}

local ICONS = {
	[CRAFTING_TYPE_BLACKSMITHING] = "/esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_blacksmithing.dds",
	[CRAFTING_TYPE_CLOTHIER] = "esoui/art/icons/mapkey/mapkey_clothier.dds",
	[CRAFTING_TYPE_ENCHANTING] = "esoui/art/icons/mapkey/mapkey_enchanter.dds",
	[CRAFTING_TYPE_ALCHEMY] = "esoui/art/icons/mapkey/mapkey_alchemist.dds",
	[CRAFTING_TYPE_PROVISIONING] = "/esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_provisioning.dds",
	[CRAFTING_TYPE_WOODWORKING] = "esoui/art/icons/mapkey/mapkey_woodworker.dds",
	[CRAFTING_TYPE_JEWELRYCRAFTING] = "esoui/art/icons/mapkey/mapkey_jewelrycrafting.dds",
}

local CRAFTING_NAMES = {
	[CRAFTING_TYPE_BLACKSMITHING] = SI_ITEMTYPEDISPLAYCATEGORY10,
	[CRAFTING_TYPE_CLOTHIER] = SI_ITEMTYPEDISPLAYCATEGORY11,
	[CRAFTING_TYPE_ENCHANTING] = SI_ITEMTYPEDISPLAYCATEGORY15,
	[CRAFTING_TYPE_ALCHEMY] = SI_ITEMTYPEDISPLAYCATEGORY14,
	[CRAFTING_TYPE_PROVISIONING] = SI_ITEMTYPEDISPLAYCATEGORY16,
	[CRAFTING_TYPE_WOODWORKING] = SI_ITEMTYPEDISPLAYCATEGORY12,
	[CRAFTING_TYPE_JEWELRYCRAFTING] = SI_ITEMTYPEDISPLAYCATEGORY13,
}

function YeOldeCrafting:GetName()
	return "YeOldeCrafting"
end

function YeOldeCrafting:InitializeControls()
	self.blocs = {}
	self.status = {}
	for _, type in ipairs(CRAFTING_ORDER) do
		self:AddCraftingBloc(type)
		if not self.SV.Show[type] then
			self.uiBar:SetBlocHidden(self.blocs[type], true)
		end
	end

	local function OnWritQuestStateChanged(craftingType, status)
		if self.SV.Show[craftingType] then
			self.status[craftingType] = status
			self.blocs[craftingType]:SetIconColor(STATUS_COLORS[status]:UnpackRGB())

			local hide = (status == STATUS.COMPLETED and self.SV.HideBlocWhenCompleted)
			self.uiBar:SetBlocHidden(self.blocs[craftingType], hide)
		end
	end

	YeOldeCraftingInventory.Initialize(self.SV)
	YeOldeQuest.Initialize()

	CALLBACK_MANAGER:RegisterCallback("YeOldeQuestStateChanged", OnWritQuestStateChanged)
end

function YeOldeCrafting:AddCraftingBloc(type)
	self.blocs[type] = self.uiBar:AddContentBloc("Writ_" .. type, ICONS[type], "")
	self.blocs[type]:SetMouseEnabled(true)
	self.status[type] = STATUS.UNKNOWN
	self.blocs[type]:SetHandler("OnMouseEnter", function(obj)
		YeOldeQuest.ShowTooltip(obj, type)
	end)

	self.blocs[type]:SetHandler("OnMouseExit", function(obj)
		ClearTooltipImmediately(InformationTooltip)
		InformationTooltip:SetDimensionConstraints(
			YeOldeInfos.ToolTip.MIN_WIDTH,
			YeOldeInfos.ToolTip.AUTO_SIZE,
			YeOldeInfos.ToolTip.MAX_WIDTH,
			YeOldeInfos.ToolTip.AUTO_SIZE
		)
	end)
end

function YeOldeCrafting:UpdateVisibility()
	local hidden = false
	if self.SV.HideWhenCompleted or self.SV.HideBlocWhenCompleted then
		local allDone = true
		for index = #CRAFTING_ORDER, 1, -1 do
			local type = CRAFTING_ORDER[index]
			if self.SV.Show[type] then
				local completed = YeOldeQuest.QuestCompleted(type)
				if self.SV.HideBlocWhenCompleted then
					self.uiBar:SetBlocHidden(self.blocs[type], completed)
				else
					self.uiBar:SetBlocHidden(self.blocs[type], false)
				end

				allDone = allDone and completed
			end
		end
		hidden = allDone
	else
		for index = #CRAFTING_ORDER, 1, -1 do
			local type = CRAFTING_ORDER[index]
			if self.SV.Show[type] then
				self.uiBar:SetBlocHidden(self.blocs[type], false)
			end
		end
	end
	self.uiBar:SetHidden(hidden and self.SV.HideWhenCompleted)
end

function YeOldeCrafting:OnActivate(value)
	YeOldeQuest.MonitorWritQuests(value)
	if value then
		self:UpdateVisibility()
	end
end

function YeOldeCrafting:InitializeSavedVars()
	-- If Version = 0, we need to initialize vars
	if self.SV.Version == 0 then
		self.SV.Show = {}
		for type, _ in pairs(CRAFTING_NAMES) do
			self.SV.Show[type] = true
		end
		self.SV.IconHeight = ICON_SIZE
		self.SV.IconWidth = ICON_SIZE
		self.SV.HideWhenCompleted = false
		self.SV.HideBlocWhenCompleted = false
		self.SV.MinCraftingMats = 500
	else
		if self.SV.IconHeight ~= ICON_SIZE then
			self.SV.IconHeight = ICON_SIZE
		end
		if self.SV.IconWidth ~= ICON_SIZE then
			self.SV.IconWidth = ICON_SIZE
		end
		if self.SV.HideWhenCompleted == nil then
			self.SV.HideWhenCompleted = false
		end
		if self.SV.HideBlocWhenCompleted == nil then
			self.SV.HideBlocWhenCompleted = false
		end
		if self.SV.MinCraftingMats == nil then
			self.SV.MinCraftingMats = 500
		end
	end

	self.SV.Version = SV_VERSION
end

function YeOldeCrafting:InitializeSettingsMenu(controls)
	controls[#controls + 1] = {
		type = "checkbox",
		name = YeOldeInfos.lang[SI_YEOLDEINFOS_HIDE_BAR_WHEN_COMPLETED],
		tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_CRAFTING_HIDE_BAR],
		getFunc = function()
			return self.SV.HideWhenCompleted
		end,
		setFunc = function(value)
			self.SV.HideWhenCompleted = value
			if not value then
				self.SV.HideBlocWhenCompleted = value
			end
			self:UpdateVisibility()
		end,
	}
	controls[#controls + 1] = {
		type = "checkbox",
		name = YeOldeInfos.lang[SI_YEOLDEINFOS_HIDE_BLOC_WHEN_COMPLETED],
		tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_CRAFTING_HIDE_BLOC],
		getFunc = function()
			return self.SV.HideBlocWhenCompleted
		end,
		setFunc = function(value)
			self.SV.HideBlocWhenCompleted = value
			if value then
				self.SV.HideWhenCompleted = value
			end
			self:UpdateVisibility()
		end,
	}
	controls[#controls + 1] = {
		type = "divider",
		reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
	}
	controls[#controls + 1] = {
		type = "description",
		title = zo_strformat(YeOldeInfos.SETTING_DESC_TITLE_PATTERN, YeOldeInfos.lang[SI_YEOLDEINFOS_BAR_CONTENT]),
		reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
	}
	for type, name in pairs(CRAFTING_NAMES) do
		controls[#controls + 1] = {
			type = "checkbox",
			name = GetString(name),
			getFunc = function()
				return self.SV.Show[type]
			end,
			setFunc = function(value)
				self.SV.Show[type] = value
				self.uiBar:SetBlocHidden(self.blocs[type], not value)
				if value then
					self:UpdateVisibility()
					if YeOldeQuest.MonitorWritQuests then
						YeOldeQuest.MonitorWritQuests(self.SV.Enabled)
					end
				end
			end,
		}
	end
	controls[#controls + 1] = {
		type = "divider",
		reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
	}
	controls[#controls + 1] = {
		type = "description",
		title = zo_strformat(YeOldeInfos.SETTING_DESC_TITLE_PATTERN, YeOldeInfos.lang[SI_YEOLDEINFOS_CRAFTING_MATS]),
		reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
	}
	controls[#controls + 1] = {
		type = "slider",
		name = YeOldeInfos.lang[SI_YEOLDEINFOS_MIN_CRAFTING_MATS],
		tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_MIN_CRAFTING_MATS],
		getFunc = function()
			return self.SV.MinCraftingMats
		end,
		setFunc = function(value)
			self.SV.MinCraftingMats = tonumber(value)
		end,
		min = 50,
		max = 2000,
		step = 50,
		decimals = 0,
		default = 500,
	}

	local options = {
		type = "submenu",
		name = GetString(SI_CRAFT_ADVISOR_TOOLTIP_WRIT_TAB),
		controls = controls,
	}
	return options
end
