---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2021-06-19 15:51
---

------------------------------------
---- constants
local SV_VERSION = 1
local ICON = "/esoui/art/collections/default/collections_default_mount.dds"
local DEFAULT_TEXT = " - "
-- Tous les icônes de skins de mounts sont disponibles dans le jeu: /esoui/art/icons/mounticon_dwarven_guar_a.dds

local COLOR_TRAIN_NOW = ZO_ColorDef:New("008800") --YeOldeInfos.Colors.GREEN
local COLOR_TRAIN_SOON = YeOldeInfos.Colors.YELLOW
local COLOR_TRAIN_LATER = YeOldeInfos.Colors.DISABLED

------------------------------------
--  YeOldeTrain Class
YeOldeTrain = YeOldeInfoBar_Base:Subclass()

function YeOldeTrain:GetName()
	return "YeOldeTrain"
end

function YeOldeTrain:InitializeControls()
	self.uiTrain = self.uiBar:AddContentBloc("TRAIN", ICON, DEFAULT_TEXT)
	self.uiBar:SetIconSize(28, 28)
	self.onUpdateFn = function()
		self:Update()
	end
	self.onRidingSkillUpdateFn = function()
		self:CheckTrainingLevels()
		self:Update()
	end
end

function YeOldeTrain:CheckTrainingLevels()
	local inventoryBonus, maxInventoryBonus, staminaBonus, maxStaminaBonus, speedBonus, maxSpeedBonus = GetRidingStats()
	self.isMaxed = (
		inventoryBonus == maxInventoryBonus
		and staminaBonus == maxStaminaBonus
		and speedBonus == maxSpeedBonus
	)
end

-- SOLID-3: Plus besoin de surcharger SetbarVisibility.
-- La base appelle GetExtraHideCondition() automatiquement.
function YeOldeTrain:GetExtraHideCondition()
	return self.hideForNow or self.isMaxed
end

function YeOldeTrain:OnActivate(value)
	self:CheckTrainingLevels()
	if value and not self.isMaxed then
		self:Update()
		EVENT_MANAGER:RegisterForUpdate(self.eventNamespace, self.SV.UpdateTime, self.onUpdateFn)
		EVENT_MANAGER:RegisterForEvent(self.eventNamespace, EVENT_RIDING_SKILL_IMPROVEMENT, self.onRidingSkillUpdateFn)
	else
		EVENT_MANAGER:UnregisterForUpdate(self.eventNamespace)
		EVENT_MANAGER:UnregisterForEvent(self.eventNamespace, EVENT_RIDING_SKILL_IMPROVEMENT)
	end
end

local function FormatTime(seconds)
	local result
	if seconds < ZO_ONE_HOUR_IN_SECONDS then
		result = zo_strformat(SI_TIME_FORMAT_MINUTES, math.floor(seconds / ZO_ONE_MINUTE_IN_SECONDS))
	else
		result = zo_strformat(SI_TIME_FORMAT_HOURS, math.floor(seconds / ZO_ONE_HOUR_IN_SECONDS))
	end
	return result
end

function YeOldeTrain:Update()
	if self.isMaxed then
		-- La barre sera cachée via GetExtraHideCondition(), on arrête juste le timer
		EVENT_MANAGER:UnregisterForUpdate(self.eventNamespace)
		self:RefreshVisibility()
		return
	end

	local timeMs, _ = GetTimeUntilCanBeTrained()

	local text = FormatTime(math.floor(timeMs / ZO_ONE_SECOND_IN_MILLISECONDS))

	if timeMs == 0 then
		self.uiTrain:SetIconColor(COLOR_TRAIN_NOW:UnpackRGB())
		self.uiTrain:SetTextColor(COLOR_TRAIN_NOW:UnpackRGB())
		self.uiTrain:SetText(GetString(SI_GAMEPAD_STABLE_TRAINABLE_READY))
	elseif timeMs < ZO_ONE_HOUR_IN_MILLISECONDS then
		self.uiTrain:SetIconColor(COLOR_TRAIN_SOON:UnpackRGB())
		self.uiTrain:SetTextColor(COLOR_TRAIN_SOON:UnpackRGB())
		self.uiTrain:SetText(text)
	else
		self.uiTrain:SetIconColor(COLOR_TRAIN_LATER:UnpackRGB())
		self.uiTrain:SetTextColor(COLOR_TRAIN_LATER:UnpackRGB())
		self.uiTrain:SetText(text)
	end

	self.hideForNow = self.SV.OnlyShowWhenReady and (timeMs > 0)
	self:RefreshVisibility()
end

function YeOldeTrain:InitializeSavedVars()
	-- If Version = 0, we need to initialize vars
	if self.SV.Version == 0 then
		self.SV.OnlyShowWhenReady = true
		self.SV.UpdateTime = 60 * ZO_ONE_SECOND_IN_MILLISECONDS
	end
	self.SV.Version = SV_VERSION
end

function YeOldeTrain:InitializeSettingsMenu(controls)
	controls[#controls + 1] = {
		type = "checkbox",
		name = YeOldeInfos.lang[SI_YEOLDEINFOS_SHOW_ONLY_IF_TRAIN],
		tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_TRAIN_READY],
		getFunc = function()
			return self.SV.OnlyShowWhenReady
		end,
		setFunc = function(value)
			self.SV.OnlyShowWhenReady = value
			self:Update()
		end,
	}

	local options = {
		type = "submenu",
		name = GetString(SI_STATS_RIDING_SKILL),
		controls = controls,
	}
	return options
end
