---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2021-06-19 13:31
---

--- Base class for all info bars
YeOldeInfoBar_Base = ZO_InitializingObject:Subclass()

local DEFAULT_FONT = "MEDIUM_FONT"
local DEFAULT_FONT_SIZE = "16"
local DEFAULT_ICON_SIZE = 26

--- Initialization method.
--- Do NOT override this method.
--- To personnalize initialization, you can override InitializeSavedVars() and InitializeControls().
function YeOldeInfoBar_Base:Initialize(name)
	self.name = name
	self.eventNamespace = YeOldeInfos.AddonName .. self.name
	self.fixedVisibility = false

	-- SOLID-1: SV management extracted to dedicated method
	self:_EnsureSavedVars()
	self:InitializeSavedVars()

	self.uiBar = YeOldeUIBar:New(self.name)
	self:InitializeControls()

	if self.uiBar:HaveStampIcon() then
		self.uiBar:ShowStampIcon(self.SV.ShowStampIcon)
	end

	if YeOldeInfos.SV.ShowExt then
		self:InitializeExtensions()
	end
end

--- Ensures the SavedVariables entry for this bar exists and is migrated.
--- Private — do not override.
function YeOldeInfoBar_Base:_EnsureSavedVars()
	if YeOldeInfos.SV.Bars[self.name] == nil then
		YeOldeInfos.SV.Bars[self.name] = {
			Version = 0,
			Enabled = true,
			Anchor = { TOPLEFT, TOPLEFT, 50, 50 },
			HideInMenu = false,
			FontType = DEFAULT_FONT,
			FontSize = DEFAULT_FONT_SIZE,
			IconScale = 1,
			ShowStampIcon = true,
			IconHeight = DEFAULT_ICON_SIZE,
			IconWidth = DEFAULT_ICON_SIZE,
		}
	else
		local sv = YeOldeInfos.SV.Bars[self.name]
		-- Remove obsolete keys
		sv.Dimension = nil
		sv.Visible = nil
		sv.Scale = nil
		sv.Font = nil
		-- Backfill missing keys for save sets older than current defaults
		if sv.FontType == nil then
			sv.FontType = DEFAULT_FONT
		end
		if sv.FontSize == nil then
			sv.FontSize = DEFAULT_FONT_SIZE
		end
		if sv.IconScale == nil then
			sv.IconScale = 1
		end
		if sv.Enabled == nil then
			sv.Enabled = true
		end
		if sv.ShowStampIcon == nil then
			sv.ShowStampIcon = true
		end
		if sv.HideInMenu == nil then
			sv.HideInMenu = false
		end
		if sv.IconHeight == nil then
			sv.IconHeight = DEFAULT_ICON_SIZE
			sv.IconWidth = DEFAULT_ICON_SIZE
		end
	end
	self.SV = YeOldeInfos.SV.Bars[self.name]
end

function YeOldeInfoBar_Base:GetName()
	-- SOLID-2: message d'erreur explicite au lieu de assert(false)
	error(string.format("[YeOldeInfos] %s must override GetName()", tostring(self.name)), 2)
end

function YeOldeInfoBar_Base:IsEnabled()
	return self.SV.Enabled
end

function YeOldeInfoBar_Base:InitializeControls()
	error(string.format("[YeOldeInfos] %s must override InitializeControls()", tostring(self.name)), 2)
end

function YeOldeInfoBar_Base:InitializeSavedVars()
	error(string.format("[YeOldeInfos] %s must override InitializeSavedVars()", tostring(self.name)), 2)
end

function YeOldeInfoBar_Base:InitializeExtensions()
	-- Unused if not overridden
end

function YeOldeInfoBar_Base:AddSettingsMenuExtensions(controls)
	-- Unused if not overridden
	return controls
end

function YeOldeInfoBar_Base:GetSettingsMenuDescription()
	return ""
end

-- Define the bar specific options
-- No need to add the "visible" option, it's already there.
--- @return table The options menu.
function YeOldeInfoBar_Base:GetSettingsMenu()
	local addonDescription = self:GetSettingsMenuDescription()

	local controls = {}
	if addonDescription ~= "" then
		controls[#controls + 1] = {
			type = "description",
			text = zo_strformat(YeOldeInfos.SETTING_DESC_CONTENT_PATTERN, addonDescription),
			reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
		}
		controls[#controls + 1] = {
			type = "divider",
			reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
		}
	end
	controls[#controls + 1] = {
		type = "checkbox",
		name = GetString(SI_ADDON_MANAGER_ENABLED),
		getFunc = function()
			return self.SV.Enabled
		end,
		setFunc = function(value)
			self:Activate(value)
		end,
	}

	controls[#controls + 1] = {
		type = "button",
		name = YeOldeInfos.lang[SI_YEOLDEINFOS_MOVE_BAR],
		tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_MOVE_BAR],
		gamepadOnly = true,
		func = function()
			self.uiBar:StartGamepadMove()
		end,
	}

	if YeOldeInfos.SV.ShowExt then
		controls = self:AddSettingsMenuExtensions(controls)
	end

	-- Add bar specific options
	return self:InitializeSettingsMenu(controls)
end

function YeOldeInfoBar_Base:InitializeSettingsMenu(controls)
	error(string.format("[YeOldeInfos] %s must override InitializeSettingsMenu()", tostring(self.name)), 2)
end

-- SOLID-3: Hook permettant aux sous-classes d'ajouter une condition de
-- visibilité supplémentaire sans avoir à surcharger SetbarVisibility entièrement.
-- Retourne true si la barre doit être cachée pour une raison propre à la sous-classe.
function YeOldeInfoBar_Base:GetExtraHideCondition()
	return false
end

-- Applies current visibility from all sources of truth without changing any SV value.
-- Combines: global settings, per-bar settings, enabled state, and extra conditions.
function YeOldeInfoBar_Base:RefreshVisibility()
	local extraHide = self:GetExtraHideCondition()
	self.uiBar:SetbarVisibility(
		YeOldeInfos.SV.HideInMenu or self.SV.HideInMenu or not self.SV.Enabled or extraHide,
		not self.SV.Enabled or extraHide
	)
end

-- Sets the per-bar saved hide settings, then refreshes.
-- Use this when the user explicitly changes per-bar visibility (e.g. from settings menu).
function YeOldeInfoBar_Base:SetbarVisibility(hideInMenu)
	self.SV.HideInMenu = hideInMenu
	self:RefreshVisibility()
end

function YeOldeInfoBar_Base:SetFontType(value)
	self.uiBar:SetFontType(value)
end

function YeOldeInfoBar_Base:SetFontSize(value)
	self.uiBar:SetFontSize(value)
end

function YeOldeInfoBar_Base:SetIconScale(value)
	self.uiBar:SetIconScale(value)
end

function YeOldeInfoBar_Base:Activate(value)
	self.SV.Enabled = value

	self:OnActivate(value)

	-- RefreshVisibility reads global + per-bar SV without overwriting them
	self:RefreshVisibility()
end

function YeOldeInfoBar_Base:OnActivate(value)
	assert(false) -- Must be overridden
end
