---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2021-06-19 15:51
---

---------- YeOlde Tasks ------------
-- TODO: Ajouter settings pour changer la couleur
-- TODO: Option pour changer la couleur du texte selon la vitesse?
------------------------------

------------------------------------
---- constants
local SV_VERSION = 2
local ICON = "/esoui/art/treeicons/gamepad/gp_emoteicon_physical.dds" --"YeOldeInfos/resources/icons/run.dds"
local ICON_SIZE = 30
local DEFAULT_TEXT = "|u10:0:: - %|u"
local FONT_STYLE = "ZoFontGameMedium"
local FONT_COLOR = { 0.8, 0.86, 0.74, 1 }
local DEFAULT_UPDATE_TIME = 100
local NORMAL_SPEED = 660

------------------------------------
---- Local functions
local function GetCurrentPos()
	local _, posX, _, posY = GetUnitRawWorldPosition("player")
	local timestamp = GetGameTimeMilliseconds()
	return { posX, posY, timestamp }
end

------------------------------------
-- YeOldeSpeed Class
YeOldeSpeed = YeOldeInfoBar_Base:Subclass()

function YeOldeSpeed:GetName()
	return "YeOldeSpeed"
end

function YeOldeSpeed:InitializeControls()
	self.uiSpeed = self.uiBar:AddContentBloc("INFO", ICON, DEFAULT_TEXT)
	self.uiBar:SetIconSize(ICON_SIZE, ICON_SIZE)
	self:SetFont()
	self.fixedVisibility = true

	self.lastPosition = GetCurrentPos()
	self.onUpdateFn = function()
		self:Update()
	end
end

function YeOldeSpeed:OnActivate(value)
	if value then
		self.lastPosition = GetCurrentPos()
		EVENT_MANAGER:RegisterForUpdate(self.eventNamespace, self.SV.UpdateTime, self.onUpdateFn)
	else
		EVENT_MANAGER:UnregisterForUpdate(self.eventNamespace)
	end
end

function YeOldeSpeed:Update()
	self.currentPosition = GetCurrentPos()
	local x1, y1, t1 = unpack(self.currentPosition)
	local x2, y2, t2 = unpack(self.lastPosition)
	local dx, dy = x1 - x2, y1 - y2
	local distance = math.sqrt(dx * dx + dy * dy)
	local timeDelta = (t1 - t2) / 1000

	if timeDelta == 0 then
		return
	end
	local rawSpeed = distance / timeDelta
	local pctSpeed = rawSpeed * 100 / self.SV.DefaultSpeed
	pctSpeed = math.floor(pctSpeed + 0.5)

	local mod = pctSpeed % 5
	pctSpeed = pctSpeed - mod

	local txt = string.format("%03d%%", pctSpeed)
	--local txtAlpha = 1
	if pctSpeed < 1 then
		txt = DEFAULT_TEXT -- DEFAULT_TEXT
		--txtAlpha = 0
	end
	--self.uiSpeed:SetTextAlpha(txtAlpha)
	self.uiSpeed:SetText(txt)
	self.lastPosition = self.currentPosition
end

function YeOldeSpeed:SetFont()
	self.uiSpeed:SetFont(FONT_STYLE)
	self.uiSpeed:SetIconColor(unpack(FONT_COLOR))
	self.uiSpeed:SetTextColor(unpack(FONT_COLOR))
end

function YeOldeSpeed:InitializeSavedVars()
	-- If Version = 0, we need to initialize vars
	if self.SV.Version == 0 then
		self.SV.UpdateTime = DEFAULT_UPDATE_TIME
		self.SV.DefaultSpeed = NORMAL_SPEED
	end
	self.SV.Version = SV_VERSION
end

function YeOldeSpeed:InitializeSettingsMenu(controls)
	controls[#controls + 1] = {
		type = "divider",
		reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
	}
	-- controls[#controls + 1] = {
	-- 	type = "description",
	-- 	title = zo_strformat(
	-- 		YeOldeInfos.SETTING_DESC_TITLE_PATTERN,
	-- 		YeOldeInfos.lang[SI_YEOLDEINFOS_SPEED_OPTIONS_DESC]
	-- 	),
	-- 	reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
	-- }
	controls[#controls + 1] = {
		type = "slider",
		name = YeOldeInfos.lang[SI_YEOLDEINFOS_SPEED_UPDATE_INTERVAL],
		tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_SPEED_UPDATE],
		getFunc = function()
			return self.SV.UpdateTime
		end,
		setFunc = function(value)
			self.SV.UpdateTime = value
			EVENT_MANAGER:UnregisterForUpdate(self.eventNamespace)
			EVENT_MANAGER:RegisterForUpdate(self.eventNamespace, self.SV.UpdateTime, self.onUpdateFn)
		end,
		min = 50,
		max = 500,
		default = DEFAULT_UPDATE_TIME,
		step = 1,
		decimals = 0,
	}
	-- controls[#controls + 1] = {
	-- 	type = "slider",
	-- 	name = YeOldeInfos.lang[SI_YEOLDEINFOS_SPEED_DEFAULT],
	-- 	tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_SPEED_CALIBRATE],
	-- 	getFunc = function()
	-- 		return self.SV.DefaultSpeed
	-- 	end,
	-- 	setFunc = function(value)
	-- 		self.SV.DefaultSpeed = value
	-- 	end,
	-- 	min = 100,
	-- 	max = 1000,
	-- 	step = 1,
	-- 	decimals = 0,
	-- 	default = NORMAL_SPEED,
	-- }

	local options = {
		type = "submenu",
		name = GetString(SI_RIDINGTRAINTYPE1),
		controls = controls,
	}
	return options
end
