---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2021-03-12 15:55
---
local ADDON_VERSION = "1.6"

local DEFAULT_FONT = "MEDIUM_FONT"
local DEFAULT_FONT_SIZE = "16"

function YeOldeInfos.IsGamepadUIActive()
	if IsInGamepadPreferredMode() then
		return true
	end
	-- Fallback for Accessibility Mode
	if GetSetting_Bool and SETTING_TYPE_ACCESSIBILITY and ACCESSIBILITY_SETTING_ACCESSIBILITY_MODE then
		return GetSetting_Bool(SETTING_TYPE_ACCESSIBILITY, ACCESSIBILITY_SETTING_ACCESSIBILITY_MODE)
	end
	return false
end

local function SetIconScale(value)
	YeOldeInfos.SV.IconScale = value
	for _, bar in pairs(YeOldeInfos.Bars) do
		bar:SetIconScale(value)
	end
end

local function SetFontSize(value)
	YeOldeInfos.SV.FontSize = value
	for _, bar in pairs(YeOldeInfos.Bars) do
		bar:SetFontSize(value)
	end
end

local function SetFontType(value)
	YeOldeInfos.SV.FontType = value
	for _, bar in pairs(YeOldeInfos.Bars) do
		bar:SetFontType(value)
	end
end

local function SetShowOptions()
	for _, bar in pairs(YeOldeInfos.Bars) do
		bar:RefreshVisibility()
	end
end

function YeOldeInfos.CreateSettingsMenu()
	local panelData = {
		type = "panel",
		name = YeOldeInfos.AddonName,
		displayName = "YeOldeInfos Settings",
		author = "|c9D2900YeOldeDragon|r",
		version = ADDON_VERSION,
		website = "https://www.esoui.com/downloads/info3122-YeOldeInfos.html",
		feedback = "https://www.esoui.com/downloads/info3122-YeOldeInfos.html#comments",
		registerForRefresh = true,
		registerForDefaults = true,
	}
	local optionsTable = {}

	if not YeOldeInfos.SV.ShowExt then
		optionsTable[#optionsTable + 1] = {
			type = "checkbox",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_HIDE_IN_MENU],
			tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_HIDE_IN_MENU],
			getFunc = function()
				return YeOldeInfos.SV.HideInMenu
			end,
			setFunc = function(value)
				YeOldeInfos.SV.HideInMenu = value
				SetShowOptions()
			end,
		}
		local fontControls = {}
		fontControls[#fontControls + 1] = {
			type = "dropdown",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_FONT_TYPE],
			tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_FONT_TYPE],
			choices = {
				"CHAT_FONT",
				"MEDIUM_FONT",
				"BOLD_FONT",
				"ANTIQUE_FONT",
				"HANDWRITTEN_FONT",
				"STONE_TABLET_FONT",
				"GAMEPAD_LIGHT_FONT",
				"GAMEPAD_MEDIUM_FONT",
				"GAMEPAD_BOLD_FONT",
			},
			getFunc = function()
				return YeOldeInfos.SV.FontType
			end,
			setFunc = function(value)
				SetFontType(value)
			end,
		}
		fontControls[#fontControls + 1] = {
			type = "slider",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_FONT_SIZE],
			tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_FONT_SIZE],
			getFunc = function()
				return YeOldeInfos.SV.FontSize
			end,
			setFunc = function(value)
				SetFontSize(value)
			end,
			min = 13,
			max = 30,
			step = 1,
			decimals = 0,
		}
		fontControls[#fontControls + 1] = {
			type = "slider",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_ICON_SIZE],
			tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_ICON_SIZE],
			getFunc = function()
				return YeOldeInfos.SV.IconScale
			end,
			setFunc = function(value)
				SetIconScale(value)
			end,
			min = 0.3,
			max = 2,
			step = 0.1,
			decimals = 1,
		}

		optionsTable[#optionsTable + 1] = {
			type = "submenu",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_FONT_OPTIONS],
			controls = fontControls,
		}
	end

	optionsTable[#optionsTable + 1] = {
		type = "divider",
		reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, YeOldeInfos.name, #optionsTable),
	}
	optionsTable[#optionsTable + 1] = {
		type = "checkbox",
		name = YeOldeInfos.Colors.GOLD:Colorize(YeOldeInfos.lang[SI_YEOLDEINFOS_SHOW_EXT_SETTINGS]),
		getFunc = function()
			return YeOldeInfos.SV.ShowExt
		end,
		setFunc = function(value)
			YeOldeInfos.SV.ShowExt = value
		end,
		requiresReload = true,
	}

	for _, bar in ipairs(YeOldeInfos.Bars) do
		optionsTable[#optionsTable + 1] = bar:GetSettingsMenu()
	end

	local LAM = LibAddonMenu2
	LAM:RegisterAddonPanel("YeOldeInfosMenu", panelData)
	LAM:RegisterOptionControls("YeOldeInfosMenu", optionsTable)
end

function YeOldeInfos.Initialize(_, addOnName)
	if addOnName ~= YeOldeInfos.AddonName then
		return
	end
	YeOldeInfos.SV = ZO_SavedVars:NewAccountWide("YeOldeInfosVars", 1.0, nil, YeOldeInfos.Default, nil)

	YeOldeInfos.Bars = {}
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldeSpeed:New("Speed")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldeCrafting:New("Crafting")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldeGolds:New("Golds")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldePlayerCurrencies:New("Currencies")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldeAccountCurrencies:New("Account")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldeMail:New("Mail")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldeInventorySpace:New("Space")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldeTime:New("Time")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldeTrain:New("Train")
	YeOldeInfos.Bars[#YeOldeInfos.Bars + 1] = YeOldePromoEvents:New("PromoEvents")

	YeOldeInfos.CreateSettingsMenu()

	local function PlayerActivated()
		for _, bar in ipairs(YeOldeInfos.Bars) do
			bar:Activate(bar:IsEnabled())
		end
	end

	EVENT_MANAGER:RegisterForEvent(YeOldeInfos.AddonName, EVENT_PLAYER_ACTIVATED, PlayerActivated)
	EVENT_MANAGER:UnregisterForEvent(YeOldeInfos.AddonName, EVENT_ADD_ON_LOADED)
end

EVENT_MANAGER:RegisterForEvent(YeOldeInfos.AddonName, EVENT_ADD_ON_LOADED, YeOldeInfos.Initialize)
