---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2021-06-19 10:13
---

-- Default values
local ICON_TEXT_OFFSET = 5
local BLOC_OFFSET = 15
local DEFAULT_ICON_SIZE = 26
local UI_BAR_PREFIX = "YeOldeUI_"
local BG_MARGIN_X_LEFT = -15
local BG_MARGIN_X_RIGHT = 30
local BG_MARGIN_Y = 20
local BLANK_TEXTURE = "/esoui/art/scrying/crystal_dot.dds"

------------------------------------
-- YeOldeUIBar Class
YeOldeUIBar = ZO_InitializingObject:Subclass()

function YeOldeUIBar:Initialize(name)
	self.SV = YeOldeInfos.SV.Bars[name]
	local anchor = self.SV.Anchor

	self.name = name
	self.uiName = UI_BAR_PREFIX .. name
	self.hideIfEmpty = false
	self.blocs = {}

	--Create the control
	self.control = _G[self.uiName] or WINDOW_MANAGER:CreateTopLevelWindow(self.uiName)
	self.control:SetClampedToScreen(true)
	self.control:SetDrawTier(DT_HIGH)
	self.control:ClearAnchors()
	self.control:SetAnchor(anchor[1], GuiRoot, anchor[2], anchor[3], anchor[4])
	self.control:SetResizeToFitDescendents(true)
	self.control:SetHidden(not self.SV.Enabled)
	self.control:SetMouseEnabled(true)
	
	-- Mouse drag to move when holding Shift
	self.control:SetHandler("OnMouseDown", function(ctrl, button)
		if button == MOUSE_BUTTON_INDEX_LEFT and IsShiftKeyDown() then
			self.control:SetMovable(true)
			self.control:StartMoving()
		end
	end)
	self.control:SetHandler("OnMouseUp", function(ctrl, button)
		if button == MOUSE_BUTTON_INDEX_LEFT then
			self.control:StopMovingOrResizing()
			self.control:SetMovable(false)
		end
	end)

	self.control:SetHandler("OnMoveStop", function(ctrl)
		local isValidAnchor, point, _, relativePoint, offsetX, offsetY = ctrl:GetAnchor()
		if isValidAnchor then
			self.SV.Anchor = { point, relativePoint, offsetX, offsetY }
		end
	end)
	self.nextBlocAnchor = self.control
	self.fragment = ZO_SimpleSceneFragment:New(self.control)

	-- Initialize scene tables
	self.menuScenes = {
		SCENE_MANAGER:GetScene("inventory"),
		SCENE_MANAGER:GetScene("bank"),
		SCENE_MANAGER:GetScene("guildBank"),
		SCENE_MANAGER:GetScene("houseBank"),
		SCENE_MANAGER:GetScene("skills"),
		SCENE_MANAGER:GetScene("achievements"),
		SCENE_MANAGER:GetScene("antiquityJournalKeyboard"),
		SCENE_MANAGER:GetScene("antiquityLoreKeyboard"),
		WORLD_MAP_SCENE,
		STATS_SCENE,
		QUEST_JOURNAL_SCENE,
		PLAYER_SUBMENU_SCENE,
		KEYBOARD_GROUP_MENU_SCENE, -- BUG-3: doublon supprimé
		CAMPAIGN_OVERVIEW_SCENE,
		CAMPAIGN_BROWSER_SCENE,
		LEADERBOARDS_SCENE,
		COMPANION_CHARACTER_KEYBOARD_SCENE,
		COMPANION_SKILLS_KEYBOARD_SCENE,
		DAILY_LOGIN_REWARDS_KEYBOARD_SCENE,
		GAME_MENU_SCENE,
		NOTIFICATIONS_SCENE, -- BUG-3: doublon supprimé
		LORE_LIBRARY_SCENE,
		COLLECTIONS_BOOK_SCENE,
		GUILD_HOME_SCENE,
		GUILD_ROSTER_SCENE,
		GUILD_RANKS_SCENE,
		GUILD_CREATE_SCENE,
		GUILD_HISTORY_SCENE,
		GUILD_HERALDRY_SCENE,
		KEYBOARD_GUILD_RECRUITMENT_SCENE,
		KEYBOARD_GUILD_BROWSER_SCENE,
		KEYBOARD_LINK_GUILD_INFO_SCENE,
		TRADING_HOUSE_SCENE, -- BUG-3: doublon supprimé
		FRIENDS_LIST_SCENE,
		MAIL_INBOX_SCENE,
		MAIL_SEND_SCENE,
		ENCHANTING_SCENE,
		SMITHING_SCENE,
		ALCHEMY_SCENE,
		PROVISIONER_SCENE,
		SCENE_MANAGER:GetScene("gamepad_options_root"),
		SCENE_MANAGER:GetScene("gamepad_options_panel"),
	}
	self.gameScenes = {
		HUD_SCENE,
		HUD_UI_SCENE,
	}
end

function YeOldeUIBar:SetbarVisibility(hideInMenu, hideInGame)
	-- PERF-1: Skip redundant scene updates if state hasn't changed
	if self._lastHideInMenu == hideInMenu and self._lastHideInGame == hideInGame then
		return
	end
	self._lastHideInMenu = hideInMenu
	self._lastHideInGame = hideInGame

	for _, scene in ipairs(self.menuScenes) do
		if hideInMenu then
			scene:RemoveFragment(self.fragment)
		else
			scene:AddFragment(self.fragment)
		end
	end
	for _, scene in ipairs(self.gameScenes) do
		if hideInGame then
			scene:RemoveFragment(self.fragment)
		else
			scene:AddFragment(self.fragment)
		end
	end
	if hideInMenu and hideInGame then
		self:SetHidden(true)
	end
end

--- Show/hide the stamp icon
---@param value boolean
function YeOldeUIBar:ShowStampIcon(value)
	for _, bloc in ipairs(self.blocs) do
		bloc:ShowStampIcon(value)
	end
end

function YeOldeUIBar:HaveStampIcon()
	local result = false
	for _, bloc in ipairs(self.blocs) do
		result = result or bloc:HaveStampIcon()
	end
	return result
end

function YeOldeUIBar:HaveText()
	local result = false
	for _, bloc in ipairs(self.blocs) do
		result = result or bloc:HaveText()
	end
	return result
end

function YeOldeUIBar:AddContentBloc(blocName, icon, text)
	local index = #self.blocs + 1
	self.blocs[index] = YeOldeUIBarContent:New(self.uiName .. "_" .. blocName, icon, text, self.nextBlocAnchor)
	self.blocs[index]:SetFont(self:GetFontFormatString())
	self.blocs[index]:SetIconSize(self.SV.IconHeight, self.SV.IconWidth, self.SV.IconScale)

	if self.nextBlocAnchor == self.control then
		self.blocs[index]:SetParentAnchor(LEFT, LEFT, 0, 0)
	end
	self.nextBlocAnchor = self.blocs[index]:GetAnchorHandler()
	return self.blocs[index]
end

function YeOldeUIBar:SetHandler(event, func)
	self.control:SetHandler(event, func)
end

--- Show/hide the ui bar.
---@param value boolean
function YeOldeUIBar:SetHidden(value)
	self.control:SetHidden(value)
end

function YeOldeUIBar:GetLastVisibleBlocIndex()
	local result = 0
	for index, bloc in ipairs(self.blocs) do
		if bloc:IsVisible() and index > result then
			result = index
		end
	end
	return result
end

--- Show/hide a Content bloc.
---@param value boolean
function YeOldeUIBar:SetBlocHidden(bloc, value)
	local lastVisibleBlocIndex = self:GetLastVisibleBlocIndex()
	for index, tmpBloc in ipairs(self.blocs) do
		if bloc.name == tmpBloc.name then
			if index < lastVisibleBlocIndex then
				if value then
					self.blocs[index + 1]:SetParentAnchor(LEFT, LEFT, 0, 0)
				else
					self.blocs[index + 1]:SetParentAnchor(LEFT, RIGHT, 0, 0)
				end
			else
				if value or index == 1 or self.blocs[index - 1]:IsHidden() then
					self.blocs[index]:SetParentAnchor(LEFT, LEFT, 0, 0)
				else
					self.blocs[index]:SetParentAnchor(LEFT, RIGHT, 0, 0)
				end
			end
			bloc:SetHidden(value)
		end
	end
	self:SetHidden(self:IsAllBlocsHidden() and self.hideIfEmpty)
end

function YeOldeUIBar:IsAllBlocsHidden()
	for _, bloc in ipairs(self.blocs) do
		if not bloc.hidden then
			return false
		end
	end
	return true
end

function YeOldeUIBar:SetHideIfEmpty(value)
	self.hideIfEmpty = value
	self:SetHidden(self:IsAllBlocsHidden() and self.hideIfEmpty)
end

---@param value string
function YeOldeUIBar:SetFontType(value)
	self.SV.FontType = value
	self._fontFormatString = nil -- PERF-3: invalider le cache
	for _, bloc in ipairs(self.blocs) do
		bloc:SetFont(self:GetFontFormatString())
	end
end

---@param value number
function YeOldeUIBar:SetFontSize(value)
	self.SV.FontSize = value
	self._fontFormatString = nil -- PERF-3: invalider le cache
	for _, bloc in ipairs(self.blocs) do
		bloc:SetFont(self:GetFontFormatString())
	end
end

---@param height number
---@param width number
function YeOldeUIBar:SetIconSize(height, width)
	self.SV.IconHeight = height
	self.SV.IconWidth = width
	for _, bloc in ipairs(self.blocs) do
		bloc:SetIconSize(height, width, self.SV.IconScale)
	end
end

---@param value number
function YeOldeUIBar:SetIconScale(value)
	self.SV.IconScale = value
	for _, bloc in ipairs(self.blocs) do
		bloc:SetIconSize(self.SV.IconHeight, self.SV.IconWidth, self.SV.IconScale)
	end
end

--- Save anchor value (in SV)
function YeOldeUIBar:SaveAnchor()
	local isValidAnchor, point, _, relativePoint, offsetX, offsetY = self.control:GetAnchor()
	if isValidAnchor then
		self.SV.Anchor = { point, relativePoint, offsetX, offsetY }
	end
end

function YeOldeUIBar:GetFontFormatString()
	-- PERF-3: retourner le cache si disponible
	if self._fontFormatString then
		return self._fontFormatString
	end
	local face = self.SV.FontType
	local size = tonumber(self.SV.FontSize)
	local shadowStyle = "|soft-shadow-thick"
	if size <= 14 then
		shadowStyle = "|soft-shadow-thin"
	end
	local fontSizeString = string.format("$(KB_%d)", size)
	self._fontFormatString = ("$(%s)|%s|%s"):format(face, fontSizeString, shadowStyle)
	return self._fontFormatString
end

------------------------------------
-- Gamepad Directional Input Movement
------------------------------------

function YeOldeUIBar:StartGamepadMove()
	if not self.SV.Enabled or not YeOldeInfos.IsGamepadUIActive() then
		return
	end

	-- Save original anchors in case of cancellation
	local isValidAnchor, point, relativeTo, relativePoint, offsetX, offsetY = self.control:GetAnchor()
	if isValidAnchor then
		self.originalAnchor = { point, relativeTo, relativePoint, offsetX, offsetY }
	else
		self.originalAnchor = nil
	end

	-- Temporarily hide the Gamepad Options menu keybinds and directional input to steal focus
	if GAMEPAD_OPTIONS then
		if DIRECTIONAL_INPUT:IsListening(GAMEPAD_OPTIONS) then
			DIRECTIONAL_INPUT:Deactivate(GAMEPAD_OPTIONS)
			self._directionalInputDeactivated = true
		end
	end

	-- Push a clean keybind state to hide all standard keybinds easily without an action layer
	self._keybindStateIndex = KEYBIND_STRIP:PushKeybindGroupState()

	-- Setup Keybind Strip
	local function SwallowInput() return true end
	self.keybindStripDescriptor = {
		alignment = KEYBIND_STRIP_ALIGN_CENTER,
		{
			name = GetString(SI_SAVE),
			keybind = "UI_SHORTCUT_PRIMARY",
			callback = function()
				zo_callLater(function() self:StopGamepadMove(true) end, 10)
				return true -- Consume input safely
			end,
		},
		{
			name = GetString(SI_CANCEL),
			keybind = "UI_SHORTCUT_NEGATIVE",
			callback = function()
				zo_callLater(function() self:StopGamepadMove(false) end, 10)
				return true -- Consume input safely
			end,
		},
		-- Swallow standard navigation inputs so nothing else moves
		{ keybind = "UI_SHORTCUT_SECONDARY", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_TERTIARY", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_UP", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_DOWN", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_LEFT", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_RIGHT", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_LEFT_TRIGGER", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_RIGHT_TRIGGER", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_LEFT_SHOULDER", callback = SwallowInput, ethereal = true },
		{ keybind = "UI_SHORTCUT_RIGHT_SHOULDER", callback = SwallowInput, ethereal = true },
	}
	KEYBIND_STRIP:AddKeybindButtonGroup(self.keybindStripDescriptor, self._keybindStateIndex)

	-- Activate Input Engine
	DIRECTIONAL_INPUT:Activate(self, self.control)

	-- Detach fragment to guarantee visibility ignoring scene states
	self.detachedFromScene = SCENE_MANAGER:GetCurrentScene()
	if self.detachedFromScene then
		self.detachedFromScene:RemoveFragment(self.fragment)
	end

	-- Force the bar to be visible during movement
	self.wasHiddenBeforeMove = self.control:IsHidden()
	self.control:SetHidden(false)

	-- Update loop
	self.control:SetHandler("OnUpdate", function()
		self:UpdateDirectionalInput()
	end)
end

function YeOldeUIBar:StopGamepadMove(savePosition)
	DIRECTIONAL_INPUT:Deactivate(self)
	self.control:SetHandler("OnUpdate", nil)
	
	if self.keybindStripDescriptor then
		if self._keybindStateIndex then
			KEYBIND_STRIP:RemoveKeybindButtonGroup(self.keybindStripDescriptor, self._keybindStateIndex)
			KEYBIND_STRIP:PopKeybindGroupState()
			self._keybindStateIndex = nil
		else
			KEYBIND_STRIP:RemoveKeybindButtonGroup(self.keybindStripDescriptor)
		end
		self.keybindStripDescriptor = nil
	end

	-- Restore Gamepad Options menu navigation
	if GAMEPAD_OPTIONS and self._directionalInputDeactivated then
		DIRECTIONAL_INPUT:Activate(GAMEPAD_OPTIONS, GAMEPAD_OPTIONS.control)
		self._directionalInputDeactivated = false
	end

	if savePosition then
		self:SaveAnchor()
	else
		if self.originalAnchor then
			local pt, rt, rp, ox, oy = unpack(self.originalAnchor)
			self.control:ClearAnchors()
			self.control:SetAnchor(pt, rt, rp, ox, oy)
		end
	end

	-- Restore fragment and visibility state
	if self.detachedFromScene then
		self.detachedFromScene:AddFragment(self.fragment)
		self.detachedFromScene = nil
	end

	if self.wasHiddenBeforeMove ~= nil then
		self.control:SetHidden(self.wasHiddenBeforeMove)
		self.wasHiddenBeforeMove = nil
	end
end

function YeOldeUIBar:UpdateDirectionalInput()
	-- Do NOT pass ZO_DI_DPAD here because it uses IsKeyDown(), which throws an insecure code error for addons
	local dx, dy = DIRECTIONAL_INPUT:GetXY(ZO_DI_LEFT_STICK)
	
	if dx ~= 0 or dy ~= 0 then
		-- Target roughly 1% to 5% of screen real-estate per analogue tick.
		-- At 60FPS, 0.01 equates to crossing the screen relative to stick pressure in under 2 seconds.
		local speedX = GuiRoot:GetWidth() * 0.01
		local speedY = GuiRoot:GetHeight() * 0.01
		
		local moveX = dx * speedX
		local moveY = -dy * speedY -- ESO Y-axis is inverted for UI coordinates

		local left = self.control:GetLeft()
		local top = self.control:GetTop()

		self.control:ClearAnchors()
		self.control:SetAnchor(TOPLEFT, GuiRoot, TOPLEFT, left + moveX, top + moveY)
	end
end

------------------------------------
--- YeOldeUIBarContent Class
YeOldeUIBarContent = ZO_InitializingObject:Subclass()

function YeOldeUIBarContent:Initialize(blocName, icon, text, parent)
	self.name = blocName
	self.parent = parent
	self.hidden = false
	self.icon = icon
	self.iconHidden = false
	self.iconWidth = DEFAULT_ICON_SIZE
	self.iconHeight = DEFAULT_ICON_SIZE

	self.baseControl = WINDOW_MANAGER:CreateControl(blocName .. "_Base", parent, CT_CONTROL)
	self.baseControl:SetAnchor(LEFT, parent, RIGHT, 0, 0)
	self.baseControl:SetResizeToFitDescendents(true)

	self.baseControl:SetHandler("OnMouseDown", function(ctrl, button)
		if button == MOUSE_BUTTON_INDEX_LEFT and IsShiftKeyDown() then
			local tlw = ctrl:GetOwningWindow()
			if type(tlw.StartMoving) == "function" then
				tlw:SetMovable(true)
				tlw:StartMoving()
			end
		end
		if self.customMouseDown then
			self.customMouseDown(ctrl, button)
		end
	end)

	self.baseControl:SetHandler("OnMouseUp", function(ctrl, button)
		if button == MOUSE_BUTTON_INDEX_LEFT then
			local tlw = ctrl:GetOwningWindow()
			tlw:StopMovingOrResizing()
			if type(tlw.SetMovable) == "function" then
				tlw:SetMovable(false)
			end
		end
		if self.customMouseUp then
			self.customMouseUp(ctrl, button)
		end
	end)

	-- Icon
	self.iconHandler = WINDOW_MANAGER:CreateControl(blocName .. "_Icon", self.baseControl, CT_TEXTURE)
	self.iconHandler:SetAnchor(LEFT, self.baseControl, LEFT, BLOC_OFFSET, 0)
	self.iconHandler:SetTexture(icon)
	self.iconHandler:SetDimensions(self.iconWidth, self.iconHeight)

	-- Text
	local offsetX = ICON_TEXT_OFFSET

	if text == "" then
		offsetX = 0
	end

	self.textHandler = WINDOW_MANAGER:CreateControl(blocName .. "_Text", self.iconHandler, CT_LABEL)
	self.textHandler:SetAnchor(LEFT, self.iconHandler, RIGHT, offsetX, 0)
	self.textHandler:SetHorizontalAlignment(CENTER)
	self.textHandler:SetVerticalAlignment(CENTER)
	-- self.textHandler:SetFontHeight(self:GetFontHeight())
	self.textHandler:SetColor(1, 1, 1)
	self.textHandler:SetText(text)
end

--- Add a small stamp icon over the bloc icon
---@param icon table Icon path
---@param whereOnParent number Anchor position
---@param offsetX table
---@param offsetY table
---@param show table Anchor default visibility
function YeOldeUIBarContent:SetStampIcon(icon, width, height, whereOnParent, offsetX, offsetY, show)
	self.iconStamp = WINDOW_MANAGER:CreateControl(self.name .. "_IconStamp", self.iconHandler, CT_TEXTURE)
	self.iconStamp:SetTexture(icon)
	self.iconStamp:SetDimensions(width, height)
	self.iconStamp:SetAnchor(whereOnParent, self.iconHandler, whereOnParent, offsetX, offsetY)

	if show == nil then -- BUG-4: condition inversée corrigée
		show = true
	end
	self:ShowStampIcon(show)
end

function YeOldeUIBarContent:HaveStampIcon()
	return self.iconStamp ~= nil
end

function YeOldeUIBarContent:SetStampIconColor(r, g, b, a)
	if self.iconStamp ~= nil then
		self.iconStamp:SetColor(r, g, b, a)
	end
end

function YeOldeUIBarContent:HaveText()
	local text = self.textHandler:GetText()
	return (text ~= nil and text ~= "")
end

--- Show/hide the stamp icon
---@param value boolean
function YeOldeUIBarContent:ShowStampIcon(value)
	if self.iconStamp ~= nil then
		self.iconStamp:SetHidden(not value)
	end
end

function YeOldeUIBarContent:SetParentAnchor(whereOnMe, whereOnParent, offsetX, offsetY)
	self.baseControl:ClearAnchors()
	self.baseControl:SetAnchor(whereOnMe, self.parent, whereOnParent, offsetX, offsetY)
end

function YeOldeUIBarContent:GetAnchorHandler()
	return self.baseControl
end

function YeOldeUIBarContent:SetHandler(event, func)
	-- CT_TEXTURE (iconHandler) doesn't support mouse events in ESO.
	-- Route handlers through baseControl (CT_CONTROL) which covers the full bloc area.
	if event == "OnMouseDown" then
		self.customMouseDown = func
	elseif event == "OnMouseUp" then
		self.customMouseUp = func
	else
		self.baseControl:SetHandler(event, func)
	end
end

function YeOldeUIBarContent:GetWidth()
	-- PERF-4: éviter l'appel double à GetText()
	local text = self.textHandler:GetText()
	local width = BLOC_OFFSET + self.iconHandler:GetWidth()
	if text ~= nil and text ~= "" then
		width = width + self.textHandler:GetWidth() + ICON_TEXT_OFFSET
	end
	return width
end

function YeOldeUIBarContent:UpdateBaseWidth()
	-- PERF-4: éviter l'appel double à GetText()
	local text = self.textHandler:GetText()
	local width = BLOC_OFFSET + self.iconHandler:GetWidth()
	if text ~= nil and text ~= "" then
		width = width + self.textHandler:GetWidth() + ICON_TEXT_OFFSET
	end
	self.baseControl:SetWidth(width)
end

function YeOldeUIBarContent:ShowIcon(value)
	if self.iconHandler ~= nil then
		if value and self.iconHidden then
			self.iconHandler:SetTexture(self.icon)
			self.iconHandler:SetDimensions(self.iconWidth, self.iconHeight)
			self.iconHidden = false
			return
		end
		if not value and not self.iconHidden then
			self.iconHandler:SetTexture(BLANK_TEXTURE)
			self.iconHandler:SetDimensions(0, 0)
			self.iconHidden = true
		end
		self:UpdateBaseWidth()
	end
end

function YeOldeUIBarContent:SetIcon(icon, width, height) -- BUG-5: ordre des paramètres corrigé (width, height)
	self.icon = icon
	self.iconWidth = width
	self.iconHeight = height
	self.iconHandler:SetTexture(icon)
	self.iconHandler:SetDimensions(width, height)
	self:UpdateBaseWidth()
end

function YeOldeUIBarContent:SetIconSize(height, width, scale)
	scale = scale or 1
	self.iconHandler:SetDimensions(height * scale, width * scale)
	local _, point, relativeTo, relativePoint, offsetX, offsetY = self.iconHandler:GetAnchor()
	self.iconHandler:SetAnchor(point, relativeTo, relativePoint, offsetX, offsetY)
	self:UpdateBaseWidth()
end

function YeOldeUIBarContent:SetMouseEnabled(isEnabled)
	self.baseControl:SetMouseEnabled(isEnabled)
	self.iconHandler:SetMouseEnabled(isEnabled)
	self.textHandler:SetMouseEnabled(isEnabled)
end

function YeOldeUIBarContent:SetIconColor(r, g, b)
	self.iconHandler:SetColor(r, g, b)
end

function YeOldeUIBarContent:SetTextColor(r, g, b)
	self.textHandler:SetColor(r, g, b)
end

function YeOldeUIBarContent:SetTextAlpha(value)
	self.textHandler:SetAlpha(value)
end

function YeOldeUIBarContent:SetHidden(value)
	self.textHandler:SetHidden(value)
	self.iconHandler:SetHidden(value)
	self.hidden = value
end

function YeOldeUIBarContent:IsHidden()
	return self.hidden
end

function YeOldeUIBarContent:IsVisible()
	return not self.hidden
end

function YeOldeUIBarContent:SetText(text)
	self.textHandler:SetText(text)

	local offsetX = ICON_TEXT_OFFSET
	if text == "" then
		offsetX = 0
	end

	local isValidAnchor, point, relativeTo, relativePoint, _, _, _ = self.textHandler:GetAnchor(0)
	if isValidAnchor then
		self.textHandler:SetAnchor(point, relativeTo, relativePoint, offsetX, 0)
	end
	self:UpdateBaseWidth()
end

--- @param font string Font name from defaultfontdefs_keyboard.xml
function YeOldeUIBarContent:SetFont(font)
	--d("YeOldeUIBarContent:SetFont: "..font)
	self.textHandler:SetFont(font)
	--self.textHandler:SetFontHeight(self:GetFontHeight())
	self:UpdateBaseWidth()
end
