---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2021-06-19 13:31
---

------------------------------
--- Class version, to update SV values when needed
-- local INFOBAR_EXT_VERSION = 1

function YeOldeInfoBar_Base:InitializeExtensions()
	if self.SV.Scale ~= nil then
		self.SV.Scale = nil
	end
end

function YeOldeInfoBar_Base:AddSettingsMenuExtensions(controls)
	if self.uiBar:HaveStampIcon() then
		controls[#controls + 1] = {
			type = "checkbox",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_SHOW_STAMP_ICON],
			tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_SHOW_STAMP_ICON],
			getFunc = function()
				return self.SV.ShowStampIcon
			end,
			setFunc = function(value)
				self.SV.ShowStampIcon = value
				self.uiBar:ShowStampIcon(value)
			end,
		}
	end
	if not self.fixedVisibility then
		controls[#controls + 1] = {
			type = "checkbox",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_HIDE_IN_MENU],
			tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_HIDE_IN_MENU],
			getFunc = function()
				return self.SV.HideInMenu
			end,
			setFunc = function(value)
				self:SetbarVisibility(value)
			end,
		}
	end

	if self.uiBar:HaveText() then
		controls[#controls + 1] = {
			type = "divider",
			reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
		}
		controls[#controls + 1] = {
			type = "description",
			title = zo_strformat(YeOldeInfos.SETTING_DESC_TITLE_PATTERN, YeOldeInfos.lang[SI_YEOLDEINFOS_FONT_OPTIONS]),
			reference = zo_strformat(YeOldeInfos.SETTING_PATTERN, self.name, #controls),
		}
		controls[#controls + 1] = {
			type = "dropdown",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_FONT_TYPE],
			tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_FONT_TYPE],
			choices = {
				"CHAT_FONT",
				"MEDIUM_FONT",
				"BOLD_FONT",
				"ANTIQUE_FONT",
				"HANDWRITTEN_FONT",
				"STONE_TABLET_FONT",
				"GAMEPAD_LIGHT_FONT",
				"GAMEPAD_MEDIUM_FONT",
				"GAMEPAD_BOLD_FONT",
			},
			getFunc = function()
				return self.SV.FontType
			end,
			setFunc = function(value)
				self.uiBar:SetFontType(value)
			end,
		}
		controls[#controls + 1] = {
			type = "slider",
			name = YeOldeInfos.lang[SI_YEOLDEINFOS_FONT_SIZE],
			tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_FONT_SIZE],
			getFunc = function()
				return self.SV.FontSize
			end,
			setFunc = function(value)
				self.uiBar:SetFontSize(value)
			end,
			min = 13,
			max = 48,
			step = 1,
			decimals = 0,
		}
	end
	controls[#controls + 1] = {
		type = "slider",
		name = YeOldeInfos.lang[SI_YEOLDEINFOS_ICON_SIZE],
		tooltip = YeOldeInfos.lang[SI_YEOLDEINFOS_TT_ICON_SIZE],
		getFunc = function()
			return self.SV.IconScale
		end,
		setFunc = function(value)
			self.uiBar:SetIconScale(value)
		end,
		min = 0.3,
		max = 2,
		step = 0.1,
		decimals = 1,
	}

	return controls
end
